ARG AIRFLOW_IMAGE=apache/airflow:2.2.4-python3.7
FROM openlineage-airflow-base:latest AS build

FROM $AIRFLOW_IMAGE AS airflow
USER root
RUN apt-get update && \
    apt-get install -y git build-essential
COPY data /opt/data
RUN chmod -R 777 /opt/data
COPY --from=build /whl /whl
USER airflow
COPY requirements.txt requirements.txt
RUN pip install --user -r requirements.txt
