FROM openlineage-airflow-base:latest AS build

FROM apache/airflow:2.1.3 AS airflow
COPY --from=build /app/wheel /whl
USER root
RUN apt-get update && \
    apt-get install -y git build-essential
RUN mkdir -p /opt/airflow
COPY data /opt/data
RUN chown -R airflow:airflow /opt/airflow
RUN chmod -R 777 /opt/data
USER airflow
COPY requirements.txt requirements.txt
RUN pip install --user -r requirements.txt

FROM openlineage-airflow-base:latest AS integration
COPY integration-requirements.txt integration-requirements.txt
COPY *.py ./
COPY requests requests
RUN pip install --use-deprecated=legacy-resolver --user -r integration-requirements.txt
COPY docker/entrypoint.sh entrypoint.sh
COPY docker/wait-for-it.sh wait-for-it.sh
ENTRYPOINT ["/entrypoint.sh"]
