##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:
  # Add '' to any changes within '' folder or any subfolders
  area:ci:
    - .circleci/**/*
    - .pre_commit/**/*
  area:client/java:
    - client/java/**/*
  area:client/python:
    - client/python/**/*
  area:dev:
    - dev/**/*
    - .github/**/*
  area:documentation:
    - doc/**/*
    - "*.md"
  area:integration/airflow:
    - integration/airflow/**/*
  area:integration/common:
    - integration/common/**/*
  area:integration/dbt:
    - integration/dbt/**/*
  area:integration/flink:
    - integration/flink/**/*
  area:integration/spark:
    - integration/spark*/**/*
  area:integration/sql:
    - integration/sql/**/*
  area:integration/hive:
    - integration/hive*/**/*
  area:proxy:
    - proxy/**/*
  area:spec:
    - spec/**/*
  area:tests:
    - "**/*test*"
  area:website:
    - website/**/*
  kind:proposal:
    - proposals/**/*
  language:java:
    - "*.java"
    - "*.jar"
  language:python:
    - "*.py"
  language:rust:
    - "*.rs"
  language:scala:
    - "*.scala"
    - "*.sc"
  skip-changelog:
    - website/**/*
    - proposals/**/*
    - doc/**/*
    - "*.md"
    - dev/**/*
    - .github/**/*
    - .circleci/**/*
    - .pre_commit/**/*

##### Greetings ########################################################################################################
# Comment to be posted to welcome users when they open their first PR
firstPRWelcomeComment: >
  Thanks for opening your first OpenLineage pull request! We appreciate your contribution. If you haven't already, please make sure you've reviewed our guide for new contributors (https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md).

# Comment to be posted to congratulate user on their first merged PR
firstPRMergeComment: >
  Great job! Congrats on your first merged pull request in OpenLineage!

# Comment to be posted to on first time issues
firstIssueWelcomeComment: >
  Thanks for creating your first OpenLineage issue! Your feedback is valuable and improves the project. If you haven't already, please be sure to follow the issue template!
