FROM python:3.7-slim
RUN mkdir /tmp/openlineage-integration-airflow
COPY python /tmp/openlineage-client-python
COPY common /tmp/openlineage-integration-common
COPY dbt /tmp/openlineage-integration-dbt
RUN cd /tmp/openlineage-client-python && pip wheel --no-deps --wheel-dir=/whl .[tests]
RUN cd /tmp/openlineage-integration-common && pip wheel --no-deps --wheel-dir=/whl .[tests]
RUN cd /tmp/openlineage-integration-dbt && pip wheel --no-deps --wheel-dir=/whl .[tests]
ADD airflow/setup.py /tmp/openlineage-integration-airflow
ADD airflow/README.md /tmp/openlineage-integration-airflow
ADD airflow/openlineage /tmp/openlineage-integration-airflow/openlineage
RUN cd /tmp/openlineage-integration-airflow && pip wheel --no-deps --wheel-dir=/whl .[tests]