/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by facet-gen. DO NOT EDIT.

package facets

import "time"

// InputDatasetFacets holds all InputDatasetFacet facets for an OpenLineage event.
type InputDatasetFacets struct {
	DataQualityAssertionsDatasetFacet *DataQualityAssertionsDatasetFacet `json:"dataQualityAssertions,omitempty"`
	DataQualityMetricsInputDatasetFacet *DataQualityMetricsInputDatasetFacet `json:"dataQualityMetrics,omitempty"`
	IcebergScanReportInputDatasetFacet *IcebergScanReportInputDatasetFacet `json:"icebergScanReport,omitempty"`
	InputStatisticsInputDatasetFacet *InputStatisticsInputDatasetFacet `json:"inputStatistics,omitempty"`
	InputSubsetInputDatasetFacet *InputSubsetInputDatasetFacet `json:"inputSubset,omitempty"`
}

// OutputDatasetFacets holds all OutputDatasetFacet facets for an OpenLineage event.
type OutputDatasetFacets struct {
	IcebergCommitReportOutputDatasetFacet *IcebergCommitReportOutputDatasetFacet `json:"icebergCommitReport,omitempty"`
	OutputStatisticsOutputDatasetFacet *OutputStatisticsOutputDatasetFacet `json:"outputStatistics,omitempty"`
	OutputSubsetOutputDatasetFacet *OutputSubsetOutputDatasetFacet `json:"outputSubset,omitempty"`
}

// DatasetFacets holds all DatasetFacet facets for an OpenLineage event.
type DatasetFacets struct {
	CatalogDatasetFacet *CatalogDatasetFacet `json:"catalog,omitempty"`
	ColumnLineageDatasetFacet *ColumnLineageDatasetFacet `json:"columnLineage,omitempty"`
	DataQualityMetricsDatasetFacet *DataQualityMetricsDatasetFacet `json:"dataQualityMetrics,omitempty"`
	DatasetTypeDatasetFacet *DatasetTypeDatasetFacet `json:"datasetType,omitempty"`
	DatasetVersionDatasetFacet *DatasetVersionDatasetFacet `json:"version,omitempty"`
	DatasourceDatasetFacet *DatasourceDatasetFacet `json:"dataSource,omitempty"`
	DocumentationDatasetFacet *DocumentationDatasetFacet `json:"documentation,omitempty"`
	HierarchyDatasetFacet *HierarchyDatasetFacet `json:"hierarchy,omitempty"`
	LifecycleStateChangeDatasetFacet *LifecycleStateChangeDatasetFacet `json:"lifecycleStateChange,omitempty"`
	OwnershipDatasetFacet *OwnershipDatasetFacet `json:"ownership,omitempty"`
	SchemaDatasetFacet *SchemaDatasetFacet `json:"schema,omitempty"`
	StorageDatasetFacet *StorageDatasetFacet `json:"storage,omitempty"`
	SymlinksDatasetFacet *SymlinksDatasetFacet `json:"symlinks,omitempty"`
	TagsDatasetFacet *TagsDatasetFacet `json:"tags,omitempty"`
}

// JobFacets holds all JobFacet facets for an OpenLineage event.
type JobFacets struct {
	DocumentationJobFacet *DocumentationJobFacet `json:"documentation,omitempty"`
	GcpComposerJobFacet *GcpComposerJobFacet `json:"gcp_composer_job,omitempty"`
	GcpLineageJobFacet *GcpLineageJobFacet `json:"gcp_lineage,omitempty"`
	JobTypeJobFacet *JobTypeJobFacet `json:"jobType,omitempty"`
	OwnershipJobFacet *OwnershipJobFacet `json:"ownership,omitempty"`
	SQLJobFacet *SQLJobFacet `json:"sql,omitempty"`
	SourceCodeJobFacet *SourceCodeJobFacet `json:"sourceCode,omitempty"`
	SourceCodeLocationJobFacet *SourceCodeLocationJobFacet `json:"sourceCodeLocation,omitempty"`
	TagsJobFacet *TagsJobFacet `json:"tags,omitempty"`
}

// RunFacets holds all RunFacet facets for an OpenLineage event.
type RunFacets struct {
	EnvironmentVariablesRunFacet *EnvironmentVariablesRunFacet `json:"environmentVariables,omitempty"`
	ErrorMessageRunFacet *ErrorMessageRunFacet `json:"errorMessage,omitempty"`
	ExecutionParametersRunFacet *ExecutionParametersRunFacet `json:"executionParameters,omitempty"`
	ExternalQueryRunFacet *ExternalQueryRunFacet `json:"externalQuery,omitempty"`
	ExtractionErrorRunFacet *ExtractionErrorRunFacet `json:"extractionError,omitempty"`
	GcpComposerRunFacet *GcpComposerRunFacet `json:"gcp_composer_run,omitempty"`
	GcpDataprocRunFacet *GcpDataprocRunFacet `json:"gcp_dataproc,omitempty"`
	JobDependenciesRunFacet *JobDependenciesRunFacet `json:"jobDependencies,omitempty"`
	NominalTimeRunFacet *NominalTimeRunFacet `json:"nominalTime,omitempty"`
	ParentRunFacet *ParentRunFacet `json:"parent,omitempty"`
	ProcessingEngineRunFacet *ProcessingEngineRunFacet `json:"processing_engine,omitempty"`
	TagsRunFacet *TagsRunFacet `json:"tags,omitempty"`
	TestRunFacet *TestRunFacet `json:"test,omitempty"`
}

var _ DatasetFacet = (*CatalogDatasetFacet)(nil)

// Apply sets this CatalogDatasetFacet facet in the DatasetFacets container.
func (f *CatalogDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).CatalogDatasetFacet = f
}

// NewCatalogDatasetFacet creates a new CatalogDatasetFacet facet.
func NewCatalogDatasetFacet(
	producer string,
	framework string,
	name string,
	typ string,
) *CatalogDatasetFacet {
	return &CatalogDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/CatalogDatasetFacet.json",
		Framework: framework,
		Name: name,
		Type: typ,
	}
}

// WithDeleted sets the Deleted field on this CatalogDatasetFacet.
func (f *CatalogDatasetFacet) WithDeleted(deleted bool) *CatalogDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithCatalogProperties sets the CatalogProperties field on this CatalogDatasetFacet.
func (f *CatalogDatasetFacet) WithCatalogProperties(catalogProperties map[string]string) *CatalogDatasetFacet {
	f.CatalogProperties = catalogProperties

	return f
}

// WithMetadataURI sets the MetadataURI field on this CatalogDatasetFacet.
func (f *CatalogDatasetFacet) WithMetadataURI(metadataURI string) *CatalogDatasetFacet {
	f.MetadataURI = &metadataURI

	return f
}

// WithSource sets the Source field on this CatalogDatasetFacet.
func (f *CatalogDatasetFacet) WithSource(source string) *CatalogDatasetFacet {
	f.Source = &source

	return f
}

// WithWarehouseURI sets the WarehouseURI field on this CatalogDatasetFacet.
func (f *CatalogDatasetFacet) WithWarehouseURI(warehouseURI string) *CatalogDatasetFacet {
	f.WarehouseURI = &warehouseURI

	return f
}

var _ DatasetFacet = (*ColumnLineageDatasetFacet)(nil)

// Apply sets this ColumnLineageDatasetFacet facet in the DatasetFacets container.
func (f *ColumnLineageDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).ColumnLineageDatasetFacet = f
}

// NewColumnLineageDatasetFacet creates a new ColumnLineageDatasetFacet facet.
func NewColumnLineageDatasetFacet(
	producer string,
) *ColumnLineageDatasetFacet {
	return &ColumnLineageDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-2-0/ColumnLineageDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this ColumnLineageDatasetFacet.
func (f *ColumnLineageDatasetFacet) WithDeleted(deleted bool) *ColumnLineageDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithDataset sets the Dataset field on this ColumnLineageDatasetFacet.
func (f *ColumnLineageDatasetFacet) WithDataset(dataset []InputField) *ColumnLineageDatasetFacet {
	f.Dataset = dataset

	return f
}

// WithFields sets the Fields field on this ColumnLineageDatasetFacet.
func (f *ColumnLineageDatasetFacet) WithFields(fields map[string]ColumnLineageDatasetFacetFieldsValue) *ColumnLineageDatasetFacet {
	f.Fields = fields

	return f
}

var _ DatasetFacet = (*DataQualityMetricsDatasetFacet)(nil)

// Apply sets this DataQualityMetricsDatasetFacet facet in the DatasetFacets container.
func (f *DataQualityMetricsDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).DataQualityMetricsDatasetFacet = f
}

// NewDataQualityMetricsDatasetFacet creates a new DataQualityMetricsDatasetFacet facet.
func NewDataQualityMetricsDatasetFacet(
	producer string,
) *DataQualityMetricsDatasetFacet {
	return &DataQualityMetricsDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/DataQualityMetricsDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithDeleted(deleted bool) *DataQualityMetricsDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithBytes sets the Bytes field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithBytes(bytes int64) *DataQualityMetricsDatasetFacet {
	f.Bytes = &bytes

	return f
}

// WithColumnMetrics sets the ColumnMetrics field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithColumnMetrics(columnMetrics map[string]DataQualityMetricsDatasetFacetColumnMetricsValue) *DataQualityMetricsDatasetFacet {
	f.ColumnMetrics = columnMetrics

	return f
}

// WithFileCount sets the FileCount field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithFileCount(fileCount int64) *DataQualityMetricsDatasetFacet {
	f.FileCount = &fileCount

	return f
}

// WithLastUpdated sets the LastUpdated field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithLastUpdated(lastUpdated *time.Time) *DataQualityMetricsDatasetFacet {
	f.LastUpdated = lastUpdated

	return f
}

// WithRowCount sets the RowCount field on this DataQualityMetricsDatasetFacet.
func (f *DataQualityMetricsDatasetFacet) WithRowCount(rowCount int64) *DataQualityMetricsDatasetFacet {
	f.RowCount = &rowCount

	return f
}

var _ DatasetFacet = (*DatasetTypeDatasetFacet)(nil)

// Apply sets this DatasetTypeDatasetFacet facet in the DatasetFacets container.
func (f *DatasetTypeDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).DatasetTypeDatasetFacet = f
}

// NewDatasetTypeDatasetFacet creates a new DatasetTypeDatasetFacet facet.
func NewDatasetTypeDatasetFacet(
	producer string,
	datasetType string,
) *DatasetTypeDatasetFacet {
	return &DatasetTypeDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/DatasetTypeDatasetFacet.json",
		DatasetType: datasetType,
	}
}

// WithDeleted sets the Deleted field on this DatasetTypeDatasetFacet.
func (f *DatasetTypeDatasetFacet) WithDeleted(deleted bool) *DatasetTypeDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithSubType sets the SubType field on this DatasetTypeDatasetFacet.
func (f *DatasetTypeDatasetFacet) WithSubType(subType string) *DatasetTypeDatasetFacet {
	f.SubType = &subType

	return f
}

var _ DatasetFacet = (*DatasetVersionDatasetFacet)(nil)

// Apply sets this DatasetVersionDatasetFacet facet in the DatasetFacets container.
func (f *DatasetVersionDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).DatasetVersionDatasetFacet = f
}

// NewDatasetVersionDatasetFacet creates a new DatasetVersionDatasetFacet facet.
func NewDatasetVersionDatasetFacet(
	producer string,
	datasetVersion string,
) *DatasetVersionDatasetFacet {
	return &DatasetVersionDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/DatasetVersionDatasetFacet.json",
		DatasetVersion: datasetVersion,
	}
}

// WithDeleted sets the Deleted field on this DatasetVersionDatasetFacet.
func (f *DatasetVersionDatasetFacet) WithDeleted(deleted bool) *DatasetVersionDatasetFacet {
	f.Deleted = &deleted

	return f
}

var _ DatasetFacet = (*DatasourceDatasetFacet)(nil)

// Apply sets this DatasourceDatasetFacet facet in the DatasetFacets container.
func (f *DatasourceDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).DatasourceDatasetFacet = f
}

// NewDatasourceDatasetFacet creates a new DatasourceDatasetFacet facet.
func NewDatasourceDatasetFacet(
	producer string,
) *DatasourceDatasetFacet {
	return &DatasourceDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/DatasourceDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this DatasourceDatasetFacet.
func (f *DatasourceDatasetFacet) WithDeleted(deleted bool) *DatasourceDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithName sets the Name field on this DatasourceDatasetFacet.
func (f *DatasourceDatasetFacet) WithName(name string) *DatasourceDatasetFacet {
	f.Name = &name

	return f
}

// WithURI sets the URI field on this DatasourceDatasetFacet.
func (f *DatasourceDatasetFacet) WithURI(uRI string) *DatasourceDatasetFacet {
	f.URI = &uRI

	return f
}

var _ DatasetFacet = (*DocumentationDatasetFacet)(nil)

// Apply sets this DocumentationDatasetFacet facet in the DatasetFacets container.
func (f *DocumentationDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).DocumentationDatasetFacet = f
}

// NewDocumentationDatasetFacet creates a new DocumentationDatasetFacet facet.
func NewDocumentationDatasetFacet(
	producer string,
	description string,
) *DocumentationDatasetFacet {
	return &DocumentationDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/DocumentationDatasetFacet.json",
		Description: description,
	}
}

// WithDeleted sets the Deleted field on this DocumentationDatasetFacet.
func (f *DocumentationDatasetFacet) WithDeleted(deleted bool) *DocumentationDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithContentType sets the ContentType field on this DocumentationDatasetFacet.
func (f *DocumentationDatasetFacet) WithContentType(contentType string) *DocumentationDatasetFacet {
	f.ContentType = &contentType

	return f
}

var _ DatasetFacet = (*HierarchyDatasetFacet)(nil)

// Apply sets this HierarchyDatasetFacet facet in the DatasetFacets container.
func (f *HierarchyDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).HierarchyDatasetFacet = f
}

// NewHierarchyDatasetFacet creates a new HierarchyDatasetFacet facet.
func NewHierarchyDatasetFacet(
	producer string,
) *HierarchyDatasetFacet {
	return &HierarchyDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/HierarchyDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this HierarchyDatasetFacet.
func (f *HierarchyDatasetFacet) WithDeleted(deleted bool) *HierarchyDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithHierarchy sets the Hierarchy field on this HierarchyDatasetFacet.
func (f *HierarchyDatasetFacet) WithHierarchy(hierarchy []HierarchyDatasetFacetLevel) *HierarchyDatasetFacet {
	f.Hierarchy = hierarchy

	return f
}

var _ DatasetFacet = (*LifecycleStateChangeDatasetFacet)(nil)

// Apply sets this LifecycleStateChangeDatasetFacet facet in the DatasetFacets container.
func (f *LifecycleStateChangeDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).LifecycleStateChangeDatasetFacet = f
}

// NewLifecycleStateChangeDatasetFacet creates a new LifecycleStateChangeDatasetFacet facet.
func NewLifecycleStateChangeDatasetFacet(
	producer string,
	lifecycleStateChange LifecycleStateChangeDatasetFacetLifecycleStateChange,
) *LifecycleStateChangeDatasetFacet {
	return &LifecycleStateChangeDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/LifecycleStateChangeDatasetFacet.json",
		LifecycleStateChange: lifecycleStateChange,
	}
}

// WithDeleted sets the Deleted field on this LifecycleStateChangeDatasetFacet.
func (f *LifecycleStateChangeDatasetFacet) WithDeleted(deleted bool) *LifecycleStateChangeDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithPreviousIdentifier sets the PreviousIdentifier field on this LifecycleStateChangeDatasetFacet.
func (f *LifecycleStateChangeDatasetFacet) WithPreviousIdentifier(previousIdentifier *LifecycleStateChangeDatasetFacetPreviousIdentifier) *LifecycleStateChangeDatasetFacet {
	f.PreviousIdentifier = previousIdentifier

	return f
}

var _ DatasetFacet = (*OwnershipDatasetFacet)(nil)

// Apply sets this OwnershipDatasetFacet facet in the DatasetFacets container.
func (f *OwnershipDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).OwnershipDatasetFacet = f
}

// NewOwnershipDatasetFacet creates a new OwnershipDatasetFacet facet.
func NewOwnershipDatasetFacet(
	producer string,
) *OwnershipDatasetFacet {
	return &OwnershipDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/OwnershipDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this OwnershipDatasetFacet.
func (f *OwnershipDatasetFacet) WithDeleted(deleted bool) *OwnershipDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithOwners sets the Owners field on this OwnershipDatasetFacet.
func (f *OwnershipDatasetFacet) WithOwners(owners []OwnershipDatasetFacetOwners) *OwnershipDatasetFacet {
	f.Owners = owners

	return f
}

var _ DatasetFacet = (*SchemaDatasetFacet)(nil)

// Apply sets this SchemaDatasetFacet facet in the DatasetFacets container.
func (f *SchemaDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).SchemaDatasetFacet = f
}

// NewSchemaDatasetFacet creates a new SchemaDatasetFacet facet.
func NewSchemaDatasetFacet(
	producer string,
) *SchemaDatasetFacet {
	return &SchemaDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-2-0/SchemaDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this SchemaDatasetFacet.
func (f *SchemaDatasetFacet) WithDeleted(deleted bool) *SchemaDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithFields sets the Fields field on this SchemaDatasetFacet.
func (f *SchemaDatasetFacet) WithFields(fields []SchemaDatasetFacetFields) *SchemaDatasetFacet {
	f.Fields = fields

	return f
}

var _ DatasetFacet = (*StorageDatasetFacet)(nil)

// Apply sets this StorageDatasetFacet facet in the DatasetFacets container.
func (f *StorageDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).StorageDatasetFacet = f
}

// NewStorageDatasetFacet creates a new StorageDatasetFacet facet.
func NewStorageDatasetFacet(
	producer string,
	storageLayer string,
) *StorageDatasetFacet {
	return &StorageDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/StorageDatasetFacet.json",
		StorageLayer: storageLayer,
	}
}

// WithDeleted sets the Deleted field on this StorageDatasetFacet.
func (f *StorageDatasetFacet) WithDeleted(deleted bool) *StorageDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithFileFormat sets the FileFormat field on this StorageDatasetFacet.
func (f *StorageDatasetFacet) WithFileFormat(fileFormat string) *StorageDatasetFacet {
	f.FileFormat = &fileFormat

	return f
}

var _ DatasetFacet = (*SymlinksDatasetFacet)(nil)

// Apply sets this SymlinksDatasetFacet facet in the DatasetFacets container.
func (f *SymlinksDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).SymlinksDatasetFacet = f
}

// NewSymlinksDatasetFacet creates a new SymlinksDatasetFacet facet.
func NewSymlinksDatasetFacet(
	producer string,
) *SymlinksDatasetFacet {
	return &SymlinksDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/SymlinksDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this SymlinksDatasetFacet.
func (f *SymlinksDatasetFacet) WithDeleted(deleted bool) *SymlinksDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithIdentifiers sets the Identifiers field on this SymlinksDatasetFacet.
func (f *SymlinksDatasetFacet) WithIdentifiers(identifiers []SymlinksDatasetFacetIdentifiers) *SymlinksDatasetFacet {
	f.Identifiers = identifiers

	return f
}

var _ DatasetFacet = (*TagsDatasetFacet)(nil)

// Apply sets this TagsDatasetFacet facet in the DatasetFacets container.
func (f *TagsDatasetFacet) Apply(facets **DatasetFacets) {
	if *facets == nil {
		*facets = &DatasetFacets{}
	}
	(*facets).TagsDatasetFacet = f
}

// NewTagsDatasetFacet creates a new TagsDatasetFacet facet.
func NewTagsDatasetFacet(
	producer string,
) *TagsDatasetFacet {
	return &TagsDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/TagsDatasetFacet.json",
	}
}

// WithDeleted sets the Deleted field on this TagsDatasetFacet.
func (f *TagsDatasetFacet) WithDeleted(deleted bool) *TagsDatasetFacet {
	f.Deleted = &deleted

	return f
}

// WithTags sets the Tags field on this TagsDatasetFacet.
func (f *TagsDatasetFacet) WithTags(tags []TagsDatasetFacetFields) *TagsDatasetFacet {
	f.Tags = tags

	return f
}

var _ InputDatasetFacet = (*DataQualityAssertionsDatasetFacet)(nil)

// Apply sets this DataQualityAssertionsDatasetFacet facet in the InputDatasetFacets container.
func (f *DataQualityAssertionsDatasetFacet) Apply(facets **InputDatasetFacets) {
	if *facets == nil {
		*facets = &InputDatasetFacets{}
	}
	(*facets).DataQualityAssertionsDatasetFacet = f
}

// NewDataQualityAssertionsDatasetFacet creates a new DataQualityAssertionsDatasetFacet facet.
func NewDataQualityAssertionsDatasetFacet(
	producer string,
) *DataQualityAssertionsDatasetFacet {
	return &DataQualityAssertionsDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/DataQualityAssertionsDatasetFacet.json",
	}
}

// WithAssertions sets the Assertions field on this DataQualityAssertionsDatasetFacet.
func (f *DataQualityAssertionsDatasetFacet) WithAssertions(assertions []DataQualityAssertionsDatasetFacetAssertions) *DataQualityAssertionsDatasetFacet {
	f.Assertions = assertions

	return f
}

var _ InputDatasetFacet = (*DataQualityMetricsInputDatasetFacet)(nil)

// Apply sets this DataQualityMetricsInputDatasetFacet facet in the InputDatasetFacets container.
func (f *DataQualityMetricsInputDatasetFacet) Apply(facets **InputDatasetFacets) {
	if *facets == nil {
		*facets = &InputDatasetFacets{}
	}
	(*facets).DataQualityMetricsInputDatasetFacet = f
}

// NewDataQualityMetricsInputDatasetFacet creates a new DataQualityMetricsInputDatasetFacet facet.
func NewDataQualityMetricsInputDatasetFacet(
	producer string,
) *DataQualityMetricsInputDatasetFacet {
	return &DataQualityMetricsInputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-3/DataQualityMetricsInputDatasetFacet.json",
	}
}

// WithBytes sets the Bytes field on this DataQualityMetricsInputDatasetFacet.
func (f *DataQualityMetricsInputDatasetFacet) WithBytes(bytes int64) *DataQualityMetricsInputDatasetFacet {
	f.Bytes = &bytes

	return f
}

// WithColumnMetrics sets the ColumnMetrics field on this DataQualityMetricsInputDatasetFacet.
func (f *DataQualityMetricsInputDatasetFacet) WithColumnMetrics(columnMetrics map[string]DataQualityMetricsInputDatasetFacetColumnMetricsValue) *DataQualityMetricsInputDatasetFacet {
	f.ColumnMetrics = columnMetrics

	return f
}

// WithFileCount sets the FileCount field on this DataQualityMetricsInputDatasetFacet.
func (f *DataQualityMetricsInputDatasetFacet) WithFileCount(fileCount int64) *DataQualityMetricsInputDatasetFacet {
	f.FileCount = &fileCount

	return f
}

// WithLastUpdated sets the LastUpdated field on this DataQualityMetricsInputDatasetFacet.
func (f *DataQualityMetricsInputDatasetFacet) WithLastUpdated(lastUpdated *time.Time) *DataQualityMetricsInputDatasetFacet {
	f.LastUpdated = lastUpdated

	return f
}

// WithRowCount sets the RowCount field on this DataQualityMetricsInputDatasetFacet.
func (f *DataQualityMetricsInputDatasetFacet) WithRowCount(rowCount int64) *DataQualityMetricsInputDatasetFacet {
	f.RowCount = &rowCount

	return f
}

var _ InputDatasetFacet = (*IcebergScanReportInputDatasetFacet)(nil)

// Apply sets this IcebergScanReportInputDatasetFacet facet in the InputDatasetFacets container.
func (f *IcebergScanReportInputDatasetFacet) Apply(facets **InputDatasetFacets) {
	if *facets == nil {
		*facets = &InputDatasetFacets{}
	}
	(*facets).IcebergScanReportInputDatasetFacet = f
}

// NewIcebergScanReportInputDatasetFacet creates a new IcebergScanReportInputDatasetFacet facet.
func NewIcebergScanReportInputDatasetFacet(
	producer string,
) *IcebergScanReportInputDatasetFacet {
	return &IcebergScanReportInputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/IcebergScanReportInputDatasetFacet.json",
	}
}

// WithFilterDescription sets the FilterDescription field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithFilterDescription(filterDescription string) *IcebergScanReportInputDatasetFacet {
	f.FilterDescription = &filterDescription

	return f
}

// WithMetadata sets the Metadata field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithMetadata(metadata map[string]string) *IcebergScanReportInputDatasetFacet {
	f.Metadata = metadata

	return f
}

// WithProjectedFieldNames sets the ProjectedFieldNames field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithProjectedFieldNames(projectedFieldNames []string) *IcebergScanReportInputDatasetFacet {
	f.ProjectedFieldNames = projectedFieldNames

	return f
}

// WithScanMetrics sets the ScanMetrics field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithScanMetrics(scanMetrics *IcebergScanReportInputDatasetFacetScanMetrics) *IcebergScanReportInputDatasetFacet {
	f.ScanMetrics = scanMetrics

	return f
}

// WithSchemaId sets the SchemaId field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithSchemaId(schemaId float64) *IcebergScanReportInputDatasetFacet {
	f.SchemaId = &schemaId

	return f
}

// WithSnapshotId sets the SnapshotId field on this IcebergScanReportInputDatasetFacet.
func (f *IcebergScanReportInputDatasetFacet) WithSnapshotId(snapshotId float64) *IcebergScanReportInputDatasetFacet {
	f.SnapshotId = &snapshotId

	return f
}

var _ InputDatasetFacet = (*InputStatisticsInputDatasetFacet)(nil)

// Apply sets this InputStatisticsInputDatasetFacet facet in the InputDatasetFacets container.
func (f *InputStatisticsInputDatasetFacet) Apply(facets **InputDatasetFacets) {
	if *facets == nil {
		*facets = &InputDatasetFacets{}
	}
	(*facets).InputStatisticsInputDatasetFacet = f
}

// NewInputStatisticsInputDatasetFacet creates a new InputStatisticsInputDatasetFacet facet.
func NewInputStatisticsInputDatasetFacet(
	producer string,
) *InputStatisticsInputDatasetFacet {
	return &InputStatisticsInputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/InputStatisticsInputDatasetFacet.json",
	}
}

// WithFileCount sets the FileCount field on this InputStatisticsInputDatasetFacet.
func (f *InputStatisticsInputDatasetFacet) WithFileCount(fileCount int64) *InputStatisticsInputDatasetFacet {
	f.FileCount = &fileCount

	return f
}

// WithRowCount sets the RowCount field on this InputStatisticsInputDatasetFacet.
func (f *InputStatisticsInputDatasetFacet) WithRowCount(rowCount int64) *InputStatisticsInputDatasetFacet {
	f.RowCount = &rowCount

	return f
}

// WithSize sets the Size field on this InputStatisticsInputDatasetFacet.
func (f *InputStatisticsInputDatasetFacet) WithSize(size int64) *InputStatisticsInputDatasetFacet {
	f.Size = &size

	return f
}

var _ InputDatasetFacet = (*InputSubsetInputDatasetFacet)(nil)

// Apply sets this InputSubsetInputDatasetFacet facet in the InputDatasetFacets container.
func (f *InputSubsetInputDatasetFacet) Apply(facets **InputDatasetFacets) {
	if *facets == nil {
		*facets = &InputDatasetFacets{}
	}
	(*facets).InputSubsetInputDatasetFacet = f
}

// NewInputSubsetInputDatasetFacet creates a new InputSubsetInputDatasetFacet facet.
func NewInputSubsetInputDatasetFacet(
	producer string,
	inputCondition RawBaseSubsetCondition,
) *InputSubsetInputDatasetFacet {
	return &InputSubsetInputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/BaseSubsetDatasetFacet.json",
		InputCondition: inputCondition,
	}
}

var _ JobFacet = (*DocumentationJobFacet)(nil)

// Apply sets this DocumentationJobFacet facet in the JobFacets container.
func (f *DocumentationJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).DocumentationJobFacet = f
}

// NewDocumentationJobFacet creates a new DocumentationJobFacet facet.
func NewDocumentationJobFacet(
	producer string,
	description string,
) *DocumentationJobFacet {
	return &DocumentationJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/DocumentationJobFacet.json",
		Description: description,
	}
}

// WithDeleted sets the Deleted field on this DocumentationJobFacet.
func (f *DocumentationJobFacet) WithDeleted(deleted bool) *DocumentationJobFacet {
	f.Deleted = &deleted

	return f
}

// WithContentType sets the ContentType field on this DocumentationJobFacet.
func (f *DocumentationJobFacet) WithContentType(contentType string) *DocumentationJobFacet {
	f.ContentType = &contentType

	return f
}

var _ JobFacet = (*GcpComposerJobFacet)(nil)

// Apply sets this GcpComposerJobFacet facet in the JobFacets container.
func (f *GcpComposerJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).GcpComposerJobFacet = f
}

// NewGcpComposerJobFacet creates a new GcpComposerJobFacet facet.
func NewGcpComposerJobFacet(
	producer string,
	airflowVersion string,
	composerVersion string,
	dagId string,
	environmentName string,
) *GcpComposerJobFacet {
	return &GcpComposerJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/GcpComposerJobFacet.json",
		AirflowVersion: airflowVersion,
		ComposerVersion: composerVersion,
		DagId: dagId,
		EnvironmentName: environmentName,
	}
}

// WithDeleted sets the Deleted field on this GcpComposerJobFacet.
func (f *GcpComposerJobFacet) WithDeleted(deleted bool) *GcpComposerJobFacet {
	f.Deleted = &deleted

	return f
}

// WithOperator sets the Operator field on this GcpComposerJobFacet.
func (f *GcpComposerJobFacet) WithOperator(operator string) *GcpComposerJobFacet {
	f.Operator = &operator

	return f
}

// WithTaskId sets the TaskId field on this GcpComposerJobFacet.
func (f *GcpComposerJobFacet) WithTaskId(taskId string) *GcpComposerJobFacet {
	f.TaskId = &taskId

	return f
}

var _ JobFacet = (*GcpLineageJobFacet)(nil)

// Apply sets this GcpLineageJobFacet facet in the JobFacets container.
func (f *GcpLineageJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).GcpLineageJobFacet = f
}

// NewGcpLineageJobFacet creates a new GcpLineageJobFacet facet.
func NewGcpLineageJobFacet(
	producer string,
) *GcpLineageJobFacet {
	return &GcpLineageJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/GcpLineageJobFacet.json",
	}
}

// WithDeleted sets the Deleted field on this GcpLineageJobFacet.
func (f *GcpLineageJobFacet) WithDeleted(deleted bool) *GcpLineageJobFacet {
	f.Deleted = &deleted

	return f
}

// WithDisplayName sets the DisplayName field on this GcpLineageJobFacet.
func (f *GcpLineageJobFacet) WithDisplayName(displayName string) *GcpLineageJobFacet {
	f.DisplayName = &displayName

	return f
}

// WithOrigin sets the Origin field on this GcpLineageJobFacet.
func (f *GcpLineageJobFacet) WithOrigin(origin *GcpLineageJobFacetOrigin) *GcpLineageJobFacet {
	f.Origin = origin

	return f
}

var _ JobFacet = (*JobTypeJobFacet)(nil)

// Apply sets this JobTypeJobFacet facet in the JobFacets container.
func (f *JobTypeJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).JobTypeJobFacet = f
}

// NewJobTypeJobFacet creates a new JobTypeJobFacet facet.
func NewJobTypeJobFacet(
	producer string,
	integration string,
	processingType string,
) *JobTypeJobFacet {
	return &JobTypeJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/2-0-3/JobTypeJobFacet.json",
		Integration: integration,
		ProcessingType: processingType,
	}
}

// WithDeleted sets the Deleted field on this JobTypeJobFacet.
func (f *JobTypeJobFacet) WithDeleted(deleted bool) *JobTypeJobFacet {
	f.Deleted = &deleted

	return f
}

// WithJobType sets the JobType field on this JobTypeJobFacet.
func (f *JobTypeJobFacet) WithJobType(jobType string) *JobTypeJobFacet {
	f.JobType = &jobType

	return f
}

var _ JobFacet = (*OwnershipJobFacet)(nil)

// Apply sets this OwnershipJobFacet facet in the JobFacets container.
func (f *OwnershipJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).OwnershipJobFacet = f
}

// NewOwnershipJobFacet creates a new OwnershipJobFacet facet.
func NewOwnershipJobFacet(
	producer string,
) *OwnershipJobFacet {
	return &OwnershipJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/OwnershipJobFacet.json",
	}
}

// WithDeleted sets the Deleted field on this OwnershipJobFacet.
func (f *OwnershipJobFacet) WithDeleted(deleted bool) *OwnershipJobFacet {
	f.Deleted = &deleted

	return f
}

// WithOwners sets the Owners field on this OwnershipJobFacet.
func (f *OwnershipJobFacet) WithOwners(owners []OwnershipJobFacetOwners) *OwnershipJobFacet {
	f.Owners = owners

	return f
}

var _ JobFacet = (*SQLJobFacet)(nil)

// Apply sets this SQLJobFacet facet in the JobFacets container.
func (f *SQLJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).SQLJobFacet = f
}

// NewSQLJobFacet creates a new SQLJobFacet facet.
func NewSQLJobFacet(
	producer string,
	query string,
) *SQLJobFacet {
	return &SQLJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/SQLJobFacet.json",
		Query: query,
	}
}

// WithDeleted sets the Deleted field on this SQLJobFacet.
func (f *SQLJobFacet) WithDeleted(deleted bool) *SQLJobFacet {
	f.Deleted = &deleted

	return f
}

// WithDialect sets the Dialect field on this SQLJobFacet.
func (f *SQLJobFacet) WithDialect(dialect string) *SQLJobFacet {
	f.Dialect = &dialect

	return f
}

var _ JobFacet = (*SourceCodeJobFacet)(nil)

// Apply sets this SourceCodeJobFacet facet in the JobFacets container.
func (f *SourceCodeJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).SourceCodeJobFacet = f
}

// NewSourceCodeJobFacet creates a new SourceCodeJobFacet facet.
func NewSourceCodeJobFacet(
	producer string,
	language string,
	sourceCode string,
) *SourceCodeJobFacet {
	return &SourceCodeJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/SourceCodeJobFacet.json",
		Language: language,
		SourceCode: sourceCode,
	}
}

// WithDeleted sets the Deleted field on this SourceCodeJobFacet.
func (f *SourceCodeJobFacet) WithDeleted(deleted bool) *SourceCodeJobFacet {
	f.Deleted = &deleted

	return f
}

var _ JobFacet = (*SourceCodeLocationJobFacet)(nil)

// Apply sets this SourceCodeLocationJobFacet facet in the JobFacets container.
func (f *SourceCodeLocationJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).SourceCodeLocationJobFacet = f
}

// NewSourceCodeLocationJobFacet creates a new SourceCodeLocationJobFacet facet.
func NewSourceCodeLocationJobFacet(
	producer string,
	typ string,
	uRL string,
) *SourceCodeLocationJobFacet {
	return &SourceCodeLocationJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/SourceCodeLocationJobFacet.json",
		Type: typ,
		URL: uRL,
	}
}

// WithDeleted sets the Deleted field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithDeleted(deleted bool) *SourceCodeLocationJobFacet {
	f.Deleted = &deleted

	return f
}

// WithBranch sets the Branch field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithBranch(branch string) *SourceCodeLocationJobFacet {
	f.Branch = &branch

	return f
}

// WithPath sets the Path field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithPath(path string) *SourceCodeLocationJobFacet {
	f.Path = &path

	return f
}

// WithPullRequestNumber sets the PullRequestNumber field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithPullRequestNumber(pullRequestNumber string) *SourceCodeLocationJobFacet {
	f.PullRequestNumber = &pullRequestNumber

	return f
}

// WithRepoURL sets the RepoURL field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithRepoURL(repoURL string) *SourceCodeLocationJobFacet {
	f.RepoURL = &repoURL

	return f
}

// WithTag sets the Tag field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithTag(tag string) *SourceCodeLocationJobFacet {
	f.Tag = &tag

	return f
}

// WithVersion sets the Version field on this SourceCodeLocationJobFacet.
func (f *SourceCodeLocationJobFacet) WithVersion(version string) *SourceCodeLocationJobFacet {
	f.Version = &version

	return f
}

var _ JobFacet = (*TagsJobFacet)(nil)

// Apply sets this TagsJobFacet facet in the JobFacets container.
func (f *TagsJobFacet) Apply(facets **JobFacets) {
	if *facets == nil {
		*facets = &JobFacets{}
	}
	(*facets).TagsJobFacet = f
}

// NewTagsJobFacet creates a new TagsJobFacet facet.
func NewTagsJobFacet(
	producer string,
) *TagsJobFacet {
	return &TagsJobFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/TagsJobFacet.json",
	}
}

// WithDeleted sets the Deleted field on this TagsJobFacet.
func (f *TagsJobFacet) WithDeleted(deleted bool) *TagsJobFacet {
	f.Deleted = &deleted

	return f
}

// WithTags sets the Tags field on this TagsJobFacet.
func (f *TagsJobFacet) WithTags(tags []TagsJobFacetFields) *TagsJobFacet {
	f.Tags = tags

	return f
}

var _ OutputDatasetFacet = (*IcebergCommitReportOutputDatasetFacet)(nil)

// Apply sets this IcebergCommitReportOutputDatasetFacet facet in the OutputDatasetFacets container.
func (f *IcebergCommitReportOutputDatasetFacet) Apply(facets **OutputDatasetFacets) {
	if *facets == nil {
		*facets = &OutputDatasetFacets{}
	}
	(*facets).IcebergCommitReportOutputDatasetFacet = f
}

// NewIcebergCommitReportOutputDatasetFacet creates a new IcebergCommitReportOutputDatasetFacet facet.
func NewIcebergCommitReportOutputDatasetFacet(
	producer string,
) *IcebergCommitReportOutputDatasetFacet {
	return &IcebergCommitReportOutputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-2/IcebergCommitReportOutputDatasetFacet.json",
	}
}

// WithCommitMetrics sets the CommitMetrics field on this IcebergCommitReportOutputDatasetFacet.
func (f *IcebergCommitReportOutputDatasetFacet) WithCommitMetrics(commitMetrics *IcebergCommitReportOutputDatasetFacetCommitMetrics) *IcebergCommitReportOutputDatasetFacet {
	f.CommitMetrics = commitMetrics

	return f
}

// WithMetadata sets the Metadata field on this IcebergCommitReportOutputDatasetFacet.
func (f *IcebergCommitReportOutputDatasetFacet) WithMetadata(metadata map[string]string) *IcebergCommitReportOutputDatasetFacet {
	f.Metadata = metadata

	return f
}

// WithOperation sets the Operation field on this IcebergCommitReportOutputDatasetFacet.
func (f *IcebergCommitReportOutputDatasetFacet) WithOperation(operation string) *IcebergCommitReportOutputDatasetFacet {
	f.Operation = &operation

	return f
}

// WithSequenceNumber sets the SequenceNumber field on this IcebergCommitReportOutputDatasetFacet.
func (f *IcebergCommitReportOutputDatasetFacet) WithSequenceNumber(sequenceNumber float64) *IcebergCommitReportOutputDatasetFacet {
	f.SequenceNumber = &sequenceNumber

	return f
}

// WithSnapshotId sets the SnapshotId field on this IcebergCommitReportOutputDatasetFacet.
func (f *IcebergCommitReportOutputDatasetFacet) WithSnapshotId(snapshotId float64) *IcebergCommitReportOutputDatasetFacet {
	f.SnapshotId = &snapshotId

	return f
}

var _ OutputDatasetFacet = (*OutputStatisticsOutputDatasetFacet)(nil)

// Apply sets this OutputStatisticsOutputDatasetFacet facet in the OutputDatasetFacets container.
func (f *OutputStatisticsOutputDatasetFacet) Apply(facets **OutputDatasetFacets) {
	if *facets == nil {
		*facets = &OutputDatasetFacets{}
	}
	(*facets).OutputStatisticsOutputDatasetFacet = f
}

// NewOutputStatisticsOutputDatasetFacet creates a new OutputStatisticsOutputDatasetFacet facet.
func NewOutputStatisticsOutputDatasetFacet(
	producer string,
) *OutputStatisticsOutputDatasetFacet {
	return &OutputStatisticsOutputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-2/OutputStatisticsOutputDatasetFacet.json",
	}
}

// WithFileCount sets the FileCount field on this OutputStatisticsOutputDatasetFacet.
func (f *OutputStatisticsOutputDatasetFacet) WithFileCount(fileCount int64) *OutputStatisticsOutputDatasetFacet {
	f.FileCount = &fileCount

	return f
}

// WithRowCount sets the RowCount field on this OutputStatisticsOutputDatasetFacet.
func (f *OutputStatisticsOutputDatasetFacet) WithRowCount(rowCount int64) *OutputStatisticsOutputDatasetFacet {
	f.RowCount = &rowCount

	return f
}

// WithSize sets the Size field on this OutputStatisticsOutputDatasetFacet.
func (f *OutputStatisticsOutputDatasetFacet) WithSize(size int64) *OutputStatisticsOutputDatasetFacet {
	f.Size = &size

	return f
}

var _ OutputDatasetFacet = (*OutputSubsetOutputDatasetFacet)(nil)

// Apply sets this OutputSubsetOutputDatasetFacet facet in the OutputDatasetFacets container.
func (f *OutputSubsetOutputDatasetFacet) Apply(facets **OutputDatasetFacets) {
	if *facets == nil {
		*facets = &OutputDatasetFacets{}
	}
	(*facets).OutputSubsetOutputDatasetFacet = f
}

// NewOutputSubsetOutputDatasetFacet creates a new OutputSubsetOutputDatasetFacet facet.
func NewOutputSubsetOutputDatasetFacet(
	producer string,
	outputCondition RawBaseSubsetCondition,
) *OutputSubsetOutputDatasetFacet {
	return &OutputSubsetOutputDatasetFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/BaseSubsetDatasetFacet.json",
		OutputCondition: outputCondition,
	}
}

var _ RunFacet = (*EnvironmentVariablesRunFacet)(nil)

// Apply sets this EnvironmentVariablesRunFacet facet in the RunFacets container.
func (f *EnvironmentVariablesRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).EnvironmentVariablesRunFacet = f
}

// NewEnvironmentVariablesRunFacet creates a new EnvironmentVariablesRunFacet facet.
func NewEnvironmentVariablesRunFacet(
	producer string,
) *EnvironmentVariablesRunFacet {
	return &EnvironmentVariablesRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/EnvironmentVariablesRunFacet.json",
	}
}

// WithEnvironmentVariables sets the EnvironmentVariables field on this EnvironmentVariablesRunFacet.
func (f *EnvironmentVariablesRunFacet) WithEnvironmentVariables(environmentVariables []EnvironmentVariable) *EnvironmentVariablesRunFacet {
	f.EnvironmentVariables = environmentVariables

	return f
}

var _ RunFacet = (*ErrorMessageRunFacet)(nil)

// Apply sets this ErrorMessageRunFacet facet in the RunFacets container.
func (f *ErrorMessageRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ErrorMessageRunFacet = f
}

// NewErrorMessageRunFacet creates a new ErrorMessageRunFacet facet.
func NewErrorMessageRunFacet(
	producer string,
	message string,
	programmingLanguage string,
) *ErrorMessageRunFacet {
	return &ErrorMessageRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/ErrorMessageRunFacet.json",
		Message: message,
		ProgrammingLanguage: programmingLanguage,
	}
}

// WithStackTrace sets the StackTrace field on this ErrorMessageRunFacet.
func (f *ErrorMessageRunFacet) WithStackTrace(stackTrace string) *ErrorMessageRunFacet {
	f.StackTrace = &stackTrace

	return f
}

var _ RunFacet = (*ExecutionParametersRunFacet)(nil)

// Apply sets this ExecutionParametersRunFacet facet in the RunFacets container.
func (f *ExecutionParametersRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ExecutionParametersRunFacet = f
}

// NewExecutionParametersRunFacet creates a new ExecutionParametersRunFacet facet.
func NewExecutionParametersRunFacet(
	producer string,
) *ExecutionParametersRunFacet {
	return &ExecutionParametersRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/ExecutionParametersRunFacet.json",
	}
}

// WithParameters sets the Parameters field on this ExecutionParametersRunFacet.
func (f *ExecutionParametersRunFacet) WithParameters(parameters []ExecutionParameter) *ExecutionParametersRunFacet {
	f.Parameters = parameters

	return f
}

var _ RunFacet = (*ExternalQueryRunFacet)(nil)

// Apply sets this ExternalQueryRunFacet facet in the RunFacets container.
func (f *ExternalQueryRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ExternalQueryRunFacet = f
}

// NewExternalQueryRunFacet creates a new ExternalQueryRunFacet facet.
func NewExternalQueryRunFacet(
	producer string,
	externalQueryId string,
	source string,
) *ExternalQueryRunFacet {
	return &ExternalQueryRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-2/ExternalQueryRunFacet.json",
		ExternalQueryId: externalQueryId,
		Source: source,
	}
}

var _ RunFacet = (*ExtractionErrorRunFacet)(nil)

// Apply sets this ExtractionErrorRunFacet facet in the RunFacets container.
func (f *ExtractionErrorRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ExtractionErrorRunFacet = f
}

// NewExtractionErrorRunFacet creates a new ExtractionErrorRunFacet facet.
func NewExtractionErrorRunFacet(
	producer string,
	failedTasks int64,
	totalTasks int64,
) *ExtractionErrorRunFacet {
	return &ExtractionErrorRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-2/ExtractionErrorRunFacet.json",
		FailedTasks: failedTasks,
		TotalTasks: totalTasks,
	}
}

// WithErrors sets the Errors field on this ExtractionErrorRunFacet.
func (f *ExtractionErrorRunFacet) WithErrors(errors []ExtractionErrorRunFacetErrors) *ExtractionErrorRunFacet {
	f.Errors = errors

	return f
}

var _ RunFacet = (*GcpComposerRunFacet)(nil)

// Apply sets this GcpComposerRunFacet facet in the RunFacets container.
func (f *GcpComposerRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).GcpComposerRunFacet = f
}

// NewGcpComposerRunFacet creates a new GcpComposerRunFacet facet.
func NewGcpComposerRunFacet(
	producer string,
	dagRunId string,
) *GcpComposerRunFacet {
	return &GcpComposerRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/GcpComposerRunFacet.json",
		DagRunId: dagRunId,
	}
}

var _ RunFacet = (*GcpDataprocRunFacet)(nil)

// Apply sets this GcpDataprocRunFacet facet in the RunFacets container.
func (f *GcpDataprocRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).GcpDataprocRunFacet = f
}

// NewGcpDataprocRunFacet creates a new GcpDataprocRunFacet facet.
func NewGcpDataprocRunFacet(
	producer string,
	appId string,
	appName string,
	projectId string,
) *GcpDataprocRunFacet {
	return &GcpDataprocRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/GcpDataprocRunFacet.json",
		AppId: appId,
		AppName: appName,
		ProjectId: projectId,
	}
}

// WithBatchId sets the BatchId field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithBatchId(batchId string) *GcpDataprocRunFacet {
	f.BatchId = &batchId

	return f
}

// WithBatchUuid sets the BatchUuid field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithBatchUuid(batchUuid string) *GcpDataprocRunFacet {
	f.BatchUuid = &batchUuid

	return f
}

// WithClusterName sets the ClusterName field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithClusterName(clusterName string) *GcpDataprocRunFacet {
	f.ClusterName = &clusterName

	return f
}

// WithClusterUuid sets the ClusterUuid field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithClusterUuid(clusterUuid string) *GcpDataprocRunFacet {
	f.ClusterUuid = &clusterUuid

	return f
}

// WithJobId sets the JobId field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithJobId(jobId string) *GcpDataprocRunFacet {
	f.JobId = &jobId

	return f
}

// WithJobType sets the JobType field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithJobType(jobType string) *GcpDataprocRunFacet {
	f.JobType = &jobType

	return f
}

// WithJobUuid sets the JobUuid field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithJobUuid(jobUuid string) *GcpDataprocRunFacet {
	f.JobUuid = &jobUuid

	return f
}

// WithQueryNodeName sets the QueryNodeName field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithQueryNodeName(queryNodeName string) *GcpDataprocRunFacet {
	f.QueryNodeName = &queryNodeName

	return f
}

// WithSessionId sets the SessionId field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithSessionId(sessionId string) *GcpDataprocRunFacet {
	f.SessionId = &sessionId

	return f
}

// WithSessionUuid sets the SessionUuid field on this GcpDataprocRunFacet.
func (f *GcpDataprocRunFacet) WithSessionUuid(sessionUuid string) *GcpDataprocRunFacet {
	f.SessionUuid = &sessionUuid

	return f
}

var _ RunFacet = (*JobDependenciesRunFacet)(nil)

// Apply sets this JobDependenciesRunFacet facet in the RunFacets container.
func (f *JobDependenciesRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).JobDependenciesRunFacet = f
}

// NewJobDependenciesRunFacet creates a new JobDependenciesRunFacet facet.
func NewJobDependenciesRunFacet(
	producer string,
) *JobDependenciesRunFacet {
	return &JobDependenciesRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/JobDependenciesRunFacet.json",
	}
}

// WithDownstream sets the Downstream field on this JobDependenciesRunFacet.
func (f *JobDependenciesRunFacet) WithDownstream(downstream []JobDependency) *JobDependenciesRunFacet {
	f.Downstream = downstream

	return f
}

// WithTrigger_rule sets the Trigger_rule field on this JobDependenciesRunFacet.
func (f *JobDependenciesRunFacet) WithTrigger_rule(trigger_rule string) *JobDependenciesRunFacet {
	f.Trigger_rule = &trigger_rule

	return f
}

// WithUpstream sets the Upstream field on this JobDependenciesRunFacet.
func (f *JobDependenciesRunFacet) WithUpstream(upstream []JobDependency) *JobDependenciesRunFacet {
	f.Upstream = upstream

	return f
}

var _ RunFacet = (*NominalTimeRunFacet)(nil)

// Apply sets this NominalTimeRunFacet facet in the RunFacets container.
func (f *NominalTimeRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).NominalTimeRunFacet = f
}

// NewNominalTimeRunFacet creates a new NominalTimeRunFacet facet.
func NewNominalTimeRunFacet(
	producer string,
	nominalStartTime time.Time,
) *NominalTimeRunFacet {
	return &NominalTimeRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/NominalTimeRunFacet.json",
		NominalStartTime: &nominalStartTime,
	}
}

// WithNominalEndTime sets the NominalEndTime field on this NominalTimeRunFacet.
func (f *NominalTimeRunFacet) WithNominalEndTime(nominalEndTime *time.Time) *NominalTimeRunFacet {
	f.NominalEndTime = nominalEndTime

	return f
}

var _ RunFacet = (*ParentRunFacet)(nil)

// Apply sets this ParentRunFacet facet in the RunFacets container.
func (f *ParentRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ParentRunFacet = f
}

// NewParentRunFacet creates a new ParentRunFacet facet.
func NewParentRunFacet(
	producer string,
	job ParentRunFacetJob,
	run ParentRunFacetRun,
) *ParentRunFacet {
	return &ParentRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-0/ParentRunFacet.json",
		Job: job,
		Run: run,
	}
}

// WithRoot sets the Root field on this ParentRunFacet.
func (f *ParentRunFacet) WithRoot(root *ParentRunFacetRoot) *ParentRunFacet {
	f.Root = root

	return f
}

var _ RunFacet = (*ProcessingEngineRunFacet)(nil)

// Apply sets this ProcessingEngineRunFacet facet in the RunFacets container.
func (f *ProcessingEngineRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).ProcessingEngineRunFacet = f
}

// NewProcessingEngineRunFacet creates a new ProcessingEngineRunFacet facet.
func NewProcessingEngineRunFacet(
	producer string,
	version string,
) *ProcessingEngineRunFacet {
	return &ProcessingEngineRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-1-1/ProcessingEngineRunFacet.json",
		Version: version,
	}
}

// WithName sets the Name field on this ProcessingEngineRunFacet.
func (f *ProcessingEngineRunFacet) WithName(name string) *ProcessingEngineRunFacet {
	f.Name = &name

	return f
}

// WithOpenlineageAdapterVersion sets the OpenlineageAdapterVersion field on this ProcessingEngineRunFacet.
func (f *ProcessingEngineRunFacet) WithOpenlineageAdapterVersion(openlineageAdapterVersion string) *ProcessingEngineRunFacet {
	f.OpenlineageAdapterVersion = &openlineageAdapterVersion

	return f
}

var _ RunFacet = (*TagsRunFacet)(nil)

// Apply sets this TagsRunFacet facet in the RunFacets container.
func (f *TagsRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).TagsRunFacet = f
}

// NewTagsRunFacet creates a new TagsRunFacet facet.
func NewTagsRunFacet(
	producer string,
) *TagsRunFacet {
	return &TagsRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-0/TagsRunFacet.json",
	}
}

// WithTags sets the Tags field on this TagsRunFacet.
func (f *TagsRunFacet) WithTags(tags []TagsRunFacetFields) *TagsRunFacet {
	f.Tags = tags

	return f
}

var _ RunFacet = (*TestRunFacet)(nil)

// Apply sets this TestRunFacet facet in the RunFacets container.
func (f *TestRunFacet) Apply(facets **RunFacets) {
	if *facets == nil {
		*facets = &RunFacets{}
	}
	(*facets).TestRunFacet = f
}

// NewTestRunFacet creates a new TestRunFacet facet.
func NewTestRunFacet(
	producer string,
) *TestRunFacet {
	return &TestRunFacet{
		Producer:  producer,
		SchemaURL: "https://openlineage.io/spec/facets/1-0-1/TestRunFacet.json",
	}
}

// WithTests sets the Tests field on this TestRunFacet.
func (f *TestRunFacet) WithTests(tests []TestExecution) *TestRunFacet {
	f.Tests = tests

	return f
}

