/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

type JobFacet int

const (
	DocumentationJobFacet JobFacet = iota
	JobTypeJobFacet
	OwnershipJobFacet
	SQLJobFacet
	SourceCodeJobFacet
	SourceCodeLocationJobFacet
	TagsJobFacet
)

type DatasetFacet int

const (
	CatalogDatasetFacet DatasetFacet = iota
	ColumnLineageDatasetFacet
	DatasetTypeDatasetFacet
	DatasetVersionDatasetFacet
	DatasourceDatasetFacet
	DocumentationDatasetFacet
	HierarchyDatasetFacet
	OwnershipDatasetFacet
	SchemaDatasetFacet
	StorageDatasetFacet
	SymlinksDatasetFacet
	TagsDatasetFacet
)

type Capability struct {
	jobEnabled     map[JobFacet]bool
	datasetEnabled map[DatasetFacet]bool
}

func (c Capability) IsJobEnabled(f JobFacet) bool         { return c.jobEnabled[f] }
func (c Capability) IsDatasetEnabled(f DatasetFacet) bool { return c.datasetEnabled[f] }
func (c Capability) isJobEnabled(f JobFacet) bool         { return c.IsJobEnabled(f) }
func (c Capability) isDatasetEnabled(f DatasetFacet) bool { return c.IsDatasetEnabled(f) }

func (c Capability) withJobFacets(fs ...JobFacet) Capability {
	jobNext := make(map[JobFacet]bool, len(c.jobEnabled)+len(fs))
	for f := range c.jobEnabled {
		jobNext[f] = true
	}
	for _, f := range fs {
		jobNext[f] = true
	}
	dsNext := make(map[DatasetFacet]bool, len(c.datasetEnabled))
	for f := range c.datasetEnabled {
		dsNext[f] = true
	}
	return Capability{jobEnabled: jobNext, datasetEnabled: dsNext}
}

func (c Capability) withDatasetFacets(fs ...DatasetFacet) Capability {
	jobNext := make(map[JobFacet]bool, len(c.jobEnabled))
	for f := range c.jobEnabled {
		jobNext[f] = true
	}
	dsNext := make(map[DatasetFacet]bool, len(c.datasetEnabled)+len(fs))
	for f := range c.datasetEnabled {
		dsNext[f] = true
	}
	for _, f := range fs {
		dsNext[f] = true
	}
	return Capability{jobEnabled: jobNext, datasetEnabled: dsNext}
}

type JobCapability struct{ Capability }

func EmptyJobCapability() JobCapability {
	return JobCapability{Capability{
		jobEnabled:     map[JobFacet]bool{},
		datasetEnabled: map[DatasetFacet]bool{},
	}}
}

func (c JobCapability) WithFacetEnabled(fs ...JobFacet) JobCapability {
	return JobCapability{c.withJobFacets(fs...)}
}

func (c JobCapability) WithDatasetFacetEnabled(fs ...DatasetFacet) JobCapability {
	return JobCapability{c.withDatasetFacets(fs...)}
}

func (c JobCapability) IsEnabled(f JobFacet) bool { return c.isJobEnabled(f) }
func (c JobCapability) IsDatasetEnabled(f DatasetFacet) bool {
	return c.isDatasetEnabled(f)
}

type DatasetCapability struct{ Capability }

func EmptyDatasetCapability() DatasetCapability {
	return DatasetCapability{Capability{
		jobEnabled:     map[JobFacet]bool{},
		datasetEnabled: map[DatasetFacet]bool{},
	}}
}

func (c DatasetCapability) WithFacetEnabled(fs ...DatasetFacet) DatasetCapability {
	return DatasetCapability{c.withDatasetFacets(fs...)}
}

func (c DatasetCapability) IsEnabled(f DatasetFacet) bool {
	return c.isDatasetEnabled(f)
}

func (c DatasetCapability) IsDatasetEnabled(f DatasetFacet) bool {
	return c.isDatasetEnabled(f)
}
