/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

import (
	"github.com/OpenLineage/openlineage/client/go/pkg/facets"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
)

// -- Interfaces ----------------------------------------------------------------

type JobFacetBuilder interface {
	BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet
}

type DatasetFacetBuilder interface {
	BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet
}

// -- Job facet dispatch --------------------------------------------------------

func (e *OpenLineageEventBuilder) buildJobFacets(data *OLJobConfig, base path.Path) []facets.JobFacet {
	type entry struct {
		facet   JobFacet
		present bool
		model   JobFacetBuilder
		pathKey string
	}

	entries := []entry{
		{DocumentationJobFacet, data.Documentation != nil, data.Documentation, "documentation"},
		{JobTypeJobFacet, data.JobType != nil, data.JobType, "job_type"},
		{OwnershipJobFacet, data.Ownership != nil, data.Ownership, "ownership"},
		{SQLJobFacet, data.SQL != nil, data.SQL, "sql"},
		{SourceCodeJobFacet, data.SourceCode != nil, data.SourceCode, "source_code"},
		{SourceCodeLocationJobFacet, data.SourceCodeLocation != nil, data.SourceCodeLocation, "source_code_location"},
		{TagsJobFacet, data.Tags != nil, data.Tags, "tags"},
	}

	var fs []facets.JobFacet
	for _, en := range entries {
		if e.cap.IsJobEnabled(en.facet) && en.present {
			if f := en.model.BuildJobFacet(e.producer, e.Diagnostics, base.AtName(en.pathKey)); f != nil {
				fs = append(fs, f)
			}
		}
	}

	return fs
}

// -- Dataset facet dispatch ----------------------------------------------------

func (e *OpenLineageEventBuilder) buildDatasetFacets(dataset *DatasetModel, base path.Path) []facets.DatasetFacet {
	type entry struct {
		facet   DatasetFacet
		present bool
		model   DatasetFacetBuilder
		pathKey string
	}

	entries := []entry{
		{CatalogDatasetFacet, dataset.Catalog != nil, dataset.Catalog, "catalog"},
		{DatasetTypeDatasetFacet, dataset.DatasetType != nil, dataset.DatasetType, "dataset_type"},
		{DatasetVersionDatasetFacet, dataset.Version != nil, dataset.Version, "version"},
		{DatasourceDatasetFacet, dataset.DataSource != nil, dataset.DataSource, "datasource"},
		{DocumentationDatasetFacet, dataset.Documentation != nil, dataset.Documentation, "documentation"},
		{HierarchyDatasetFacet, dataset.Hierarchy != nil, dataset.Hierarchy, "hierarchy"},
		{OwnershipDatasetFacet, dataset.Ownership != nil, dataset.Ownership, "ownership"},
		{SchemaDatasetFacet, dataset.Schema != nil, dataset.Schema, "schema"},
		{StorageDatasetFacet, dataset.Storage != nil, dataset.Storage, "storage"},
		{SymlinksDatasetFacet, dataset.Symlinks != nil, dataset.Symlinks, "symlinks"},
		{TagsDatasetFacet, dataset.Tags != nil, dataset.Tags, "tags"},
	}

	var fs []facets.DatasetFacet
	for _, en := range entries {
		if e.cap.IsDatasetEnabled(en.facet) && en.present {
			if f := en.model.BuildDatasetFacet(e.producer, e.Diagnostics, base.AtName(en.pathKey)); f != nil {
				fs = append(fs, f)
			}
		}
	}

	return fs
}
