/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BlockKind int

const (
	SingleBlock BlockKind = iota
	ListBlock
)

type FacetSchemaDescriptor struct {
	JobFacet     JobFacet
	DatasetFacet DatasetFacet

	Key       string
	BlockKind BlockKind
	Build     func() schema.Block
}

var JobFacetSchemas = []FacetSchemaDescriptor{
	{JobFacet: DocumentationJobFacet, Key: "documentation_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return documentationJobBlock() }},
	{JobFacet: JobTypeJobFacet, Key: "job_type_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return jobTypeJobBlock() }},
	{JobFacet: OwnershipJobFacet, Key: "ownership_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return ownershipJobBlock() }},
	{JobFacet: SQLJobFacet, Key: "s_q_l_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return sQLJobBlock() }},
	{JobFacet: SourceCodeJobFacet, Key: "source_code_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return sourceCodeJobBlock() }},
	{JobFacet: SourceCodeLocationJobFacet, Key: "source_code_location_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return sourceCodeLocationJobBlock() }},
	{JobFacet: TagsJobFacet, Key: "tags_job_facet", BlockKind: SingleBlock, Build: func() schema.Block { return tagsJobBlock() }},
}

var DatasetFacetSchemas = []FacetSchemaDescriptor{
	{DatasetFacet: CatalogDatasetFacet, Key: "catalog_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return catalogDatasetBlock() }},
	{DatasetFacet: ColumnLineageDatasetFacet, Key: "column_lineage_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return columnLineageDatasetBlock() }},
	{DatasetFacet: DatasetTypeDatasetFacet, Key: "dataset_type_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return datasetTypeDatasetBlock() }},
	{DatasetFacet: DatasetVersionDatasetFacet, Key: "dataset_version_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return datasetVersionDatasetBlock() }},
	{DatasetFacet: DatasourceDatasetFacet, Key: "datasource_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return datasourceDatasetBlock() }},
	{DatasetFacet: DocumentationDatasetFacet, Key: "documentation_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return documentationDatasetBlock() }},
	{DatasetFacet: HierarchyDatasetFacet, Key: "hierarchy_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return hierarchyDatasetBlock() }},
	{DatasetFacet: OwnershipDatasetFacet, Key: "ownership_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return ownershipDatasetBlock() }},
	{DatasetFacet: SchemaDatasetFacet, Key: "schema_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return schemaDatasetBlock() }},
	{DatasetFacet: StorageDatasetFacet, Key: "storage_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return storageDatasetBlock() }},
	{DatasetFacet: SymlinksDatasetFacet, Key: "symlinks_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return symlinksDatasetBlock() }},
	{DatasetFacet: TagsDatasetFacet, Key: "tags_dataset_facet", BlockKind: SingleBlock, Build: func() schema.Block { return tagsDatasetBlock() }},
}

func catalogDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"catalog_properties": schema.MapAttribute{Optional: true, Description: "Additional catalog properties", ElementType: types.StringType},
			"framework":          requiredString("The storage framework for which the catalog is configured"),
			"metadata_uri":       optionalString("URI or connection string to the catalog, if applicable."),
			"name":               requiredString("Name of the catalog, as configured in the source system."),
			"source":             optionalString("Source system where the catalog is configured."),
			"type":               requiredString("Type of the catalog."),
			"warehouse_uri":      optionalString("URI or connection string to the physical location of the data that the catalog describes."),
		},
		Validators: requireFields(
			"framework",
			"name",
			"type",
		),
	}
}

func columnLineageDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"dataset": schema.ListNestedBlock{
				Description: "Represents a single dependency on some field (column).",
				Validators:  []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"field":     requiredString("The input field"),
						"name":      requiredString("The input dataset name"),
						"namespace": requiredString("The input dataset namespace"),
					},
					Blocks: map[string]schema.Block{
						"transformations": schema.ListNestedBlock{
							Validators: []validator.List{listvalidator.SizeAtLeast(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"description": optionalString("a string representation of the transformation applied"),
									"masking":     schema.BoolAttribute{Optional: true, Description: "is transformation masking the data or not"},
									"subtype":     optionalString("The subtype of the transformation"),
									"type":        requiredString("The type of the transformation. Allowed values are: DIRECT, INDIRECT"),
								},
								Validators: requireFields(
									"type",
								),
							},
						},
					},
					Validators: requireFields(
						"field",
						"name",
						"namespace",
					),
				},
			},
			"fields": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": requiredString("Map key"),
					},
					Blocks: map[string]schema.Block{
						"input_fields": schema.ListNestedBlock{
							Description: "Represents a single dependency on some field (column).",
							Validators:  []validator.List{listvalidator.SizeAtLeast(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"field":     requiredString("The input field"),
									"name":      requiredString("The input dataset name"),
									"namespace": requiredString("The input dataset namespace"),
								},
								Blocks: map[string]schema.Block{
									"transformations": schema.ListNestedBlock{
										Validators: []validator.List{listvalidator.SizeAtLeast(1)},
										NestedObject: schema.NestedBlockObject{
											Attributes: map[string]schema.Attribute{
												"description": optionalString("a string representation of the transformation applied"),
												"masking":     schema.BoolAttribute{Optional: true, Description: "is transformation masking the data or not"},
												"subtype":     optionalString("The subtype of the transformation"),
												"type":        requiredString("The type of the transformation. Allowed values are: DIRECT, INDIRECT"),
											},
											Validators: requireFields(
												"type",
											),
										},
									},
								},
								Validators: requireFields(
									"field",
									"name",
									"namespace",
								),
							},
						},
					},
					Validators: requireFields(
						"input_fields",
					),
				},
			},
		},
		Validators: requireFields(
			"fields",
		),
	}
}

func datasetTypeDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"dataset_type": requiredString("Dataset type, for example: TABLE|VIEW|FILE|TOPIC|STREAM|MODEL|JOB_OUTPUT."),
			"sub_type":     optionalString("Optional sub-type within the dataset type (e.g., MATERIALIZED, EXTERNAL, TEMPORARY)."),
		},
		Validators: requireFields(
			"dataset_type",
		),
	}
}

func datasetVersionDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"dataset_version": requiredString("The version of the dataset."),
		},
		Validators: requireFields(
			"dataset_version",
		),
	}
}

func datasourceDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"name": optionalString(""),
			"uri":  optionalString(""),
		},
	}
}

func documentationDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"content_type": optionalString("MIME type of the description field content."),
			"description":  requiredString("The description of the dataset."),
		},
		Validators: requireFields(
			"description",
		),
	}
}

func documentationJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"content_type": optionalString("MIME type of the description field content."),
			"description":  requiredString("The description of the job."),
		},
		Validators: requireFields(
			"description",
		),
	}
}

func hierarchyDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"hierarchy": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": requiredString("Dataset hierarchy level name"),
						"type": requiredString("Dataset hierarchy level type"),
					},
					Validators: requireFields(
						"name",
						"type",
					),
				},
			},
		},
		Validators: requireFields(
			"hierarchy",
		),
	}
}

func jobTypeJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"integration":     requiredString("OpenLineage integration type of this job: for example SPARK|DBT|AIRFLOW|FLINK"),
			"job_type":        optionalString("Run type, for example: QUERY|COMMAND|DAG|TASK|JOB|MODEL. This is an integration-specific field."),
			"processing_type": requiredString("Job processing type like: BATCH or STREAMING"),
		},
		Validators: requireFields(
			"integration",
			"processing_type",
		),
	}
}

func ownershipDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"owners": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": requiredString("the identifier of the owner of the Dataset. It is recommended to define this as a URN. For example application:foo, user:jdoe, team:data"),
						"type": optionalString("The type of ownership (optional)"),
					},
					Validators: requireFields(
						"name",
					),
				},
			},
		},
	}
}

func ownershipJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"owners": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": requiredString("the identifier of the owner of the Job. It is recommended to define this as a URN. For example application:foo, user:jdoe, team:data"),
						"type": optionalString("The type of ownership (optional)"),
					},
					Validators: requireFields(
						"name",
					),
				},
			},
		},
	}
}

func sQLJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"dialect": optionalString(""),
			"query":   requiredString(""),
		},
		Validators: requireFields(
			"query",
		),
	}
}

func schemaDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"fields": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"description":      optionalString("The description of the field."),
						"name":             requiredString("The name of the field."),
						"ordinal_position": schema.Int64Attribute{Optional: true, Description: "The ordinal position of the field in the schema (1-indexed)."},
						"type":             optionalString("The type of the field."),
					},
					Blocks: map[string]schema.Block{
						"fields": schema.ListNestedBlock{},
					},
					Validators: requireFields(
						"name",
					),
				},
			},
		},
	}
}

func sourceCodeJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"language":    requiredString("Language in which source code of this job was written."),
			"source_code": requiredString("Source code of this job."),
		},
		Validators: requireFields(
			"language",
			"source_code",
		),
	}
}

func sourceCodeLocationJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"branch":              optionalString("optional branch name"),
			"path":                optionalString("the path in the repo containing the source files"),
			"pull_request_number": optionalString("optional pull request or merge request number associated with a CI run, populated from CI platform environment variables (e.g. GITHUB_REF, CI_MERGE_REQUEST_IID)"),
			"repo_url":            optionalString("the URL to the repository"),
			"tag":                 optionalString("optional tag name"),
			"type":                requiredString("the source control system"),
			"url":                 requiredString("the full http URL to locate the file"),
			"version":             optionalString("the current version deployed (not a branch name, the actual unique version)"),
		},
		Validators: requireFields(
			"type",
			"url",
		),
	}
}

func storageDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Attributes: map[string]schema.Attribute{
			"file_format":   optionalString("File format with allowed values: parquet, orc, avro, json, csv, text, xml."),
			"storage_layer": requiredString("Storage layer provider with allowed values: iceberg, delta."),
		},
		Validators: requireFields(
			"storage_layer",
		),
	}
}

func symlinksDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"identifiers": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name":      requiredString("The dataset name"),
						"namespace": requiredString("The dataset namespace"),
						"type":      requiredString("Identifier type"),
					},
					Validators: requireFields(
						"name",
						"namespace",
						"type",
					),
				},
			},
		},
	}
}

func tagsDatasetBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"tags": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"field":  optionalString("Identifies the field in a dataset if a tag applies to one"),
						"key":    requiredString("Key that identifies the tag"),
						"source": optionalString("The source of the tag. INTEGRATION|USER|DBT CORE|SPARK|etc."),
						"value":  requiredString("The value of the field"),
					},
					Validators: requireFields(
						"key",
						"value",
					),
				},
			},
		},
	}
}

func tagsJobBlock() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{
		Blocks: map[string]schema.Block{
			"tags": schema.ListNestedBlock{
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"key":    requiredString("Key that identifies the tag"),
						"source": optionalString("The source of the tag. INTEGRATION|USER|DBT CORE|SPARK|etc."),
						"value":  requiredString("The value of the field"),
					},
					Validators: requireFields(
						"key",
						"value",
					),
				},
			},
		},
	}
}
