/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

import (
	"github.com/OpenLineage/openlineage/client/go/pkg/facets"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
)

func (m *CatalogDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewCatalogDatasetFacet(
		producer,
		RequiredStringValue(diags, m.Framework, base.AtName("framework")),
		RequiredStringValue(diags, m.Name, base.AtName("name")),
		RequiredStringValue(diags, m.Type, base.AtName("type")),
	)
	if len(m.CatalogProperties) > 0 {
		_mCatalogProperties := make(map[string]string, len(m.CatalogProperties))
		for k, v := range m.CatalogProperties {
			if !v.IsNull() && !v.IsUnknown() {
				_mCatalogProperties[k] = v.ValueString()
			}
		}
		if len(_mCatalogProperties) > 0 {
			f.CatalogProperties = _mCatalogProperties
		}
	}
	f.MetadataURI = OptionalStringValue(m.MetadataUri)
	f.Source = OptionalStringValue(m.Source)
	f.WarehouseURI = OptionalStringValue(m.WarehouseUri)
	return f
}

func (m *ColumnLineageDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	_map1 := make(map[string]facets.ColumnLineageDatasetFacetFieldsValue, len(m.Fields))
	for _k1, _item1 := range m.Fields {
		_p1 := base.AtName("fields").AtMapKey(_k1)
		inputField := make([]facets.InputField, 0, len(_item1.InputFields))
		for _i2, _item2 := range _item1.InputFields {
			_p2 := _p1.AtName("input_fields").AtListIndex(_i2)
			inputFieldTransformation := make([]facets.InputFieldTransformation, 0, len(_item2.Transformations))
			for _i3, _item3 := range _item2.Transformations {
				_p3 := _p2.AtName("transformations").AtListIndex(_i3)
				inputFieldTransformation = append(inputFieldTransformation, facets.InputFieldTransformation{
					Description: OptionalStringValue(_item3.Description),
					Masking:     OptionalBoolValue(_item3.Masking),
					Subtype:     OptionalStringValue(_item3.Subtype),
					Type:        RequiredStringValue(diags, _item3.Type, _p3.AtName("type")),
				})
			}
			inputField = append(inputField, facets.InputField{
				Field:           RequiredStringValue(diags, _item2.Field, _p2.AtName("field")),
				Name:            RequiredStringValue(diags, _item2.Name, _p2.AtName("name")),
				Namespace:       RequiredStringValue(diags, _item2.Namespace, _p2.AtName("namespace")),
				Transformations: inputFieldTransformation,
			})
		}
		_map1[_k1] = facets.ColumnLineageDatasetFacetFieldsValue{
			InputFields: inputField,
		}
	}
	f := facets.NewColumnLineageDatasetFacet(
		producer,
		_map1,
	)
	inputField2 := make([]facets.InputField, 0, len(m.Dataset))
	for _i4, _item4 := range m.Dataset {
		_p4 := base.AtName("dataset").AtListIndex(_i4)
		inputFieldTransformation2 := make([]facets.InputFieldTransformation, 0, len(_item4.Transformations))
		for _i5, _item5 := range _item4.Transformations {
			_p5 := _p4.AtName("transformations").AtListIndex(_i5)
			inputFieldTransformation2 = append(inputFieldTransformation2, facets.InputFieldTransformation{
				Description: OptionalStringValue(_item5.Description),
				Masking:     OptionalBoolValue(_item5.Masking),
				Subtype:     OptionalStringValue(_item5.Subtype),
				Type:        RequiredStringValue(diags, _item5.Type, _p5.AtName("type")),
			})
		}
		inputField2 = append(inputField2, facets.InputField{
			Field:           RequiredStringValue(diags, _item4.Field, _p4.AtName("field")),
			Name:            RequiredStringValue(diags, _item4.Name, _p4.AtName("name")),
			Namespace:       RequiredStringValue(diags, _item4.Namespace, _p4.AtName("namespace")),
			Transformations: inputFieldTransformation2,
		})
	}
	f.Dataset = inputField2
	return f
}

func (m *DatasetTypeDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewDatasetTypeDatasetFacet(
		producer,
		RequiredStringValue(diags, m.DatasetType, base.AtName("dataset_type")),
	)
	f.SubType = OptionalStringValue(m.SubType)
	return f
}

func (m *DatasetVersionDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewDatasetVersionDatasetFacet(
		producer,
		RequiredStringValue(diags, m.DatasetVersion, base.AtName("dataset_version")),
	)
	return f
}

func (m *DatasourceDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewDatasourceDatasetFacet(
		producer,
	)
	f.Name = OptionalStringValue(m.Name)
	f.URI = OptionalStringValue(m.Uri)
	return f
}

func (m *DocumentationDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewDocumentationDatasetFacet(
		producer,
		RequiredStringValue(diags, m.Description, base.AtName("description")),
	)
	f.ContentType = OptionalStringValue(m.ContentType)
	return f
}

func (m *HierarchyDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	hierarchyDatasetFacetLevel := make([]facets.HierarchyDatasetFacetLevel, 0, len(m.Hierarchy))
	for _i1, _item1 := range m.Hierarchy {
		_p1 := base.AtName("hierarchy").AtListIndex(_i1)
		hierarchyDatasetFacetLevel = append(hierarchyDatasetFacetLevel, facets.HierarchyDatasetFacetLevel{
			Name: RequiredStringValue(diags, _item1.Name, _p1.AtName("name")),
			Type: RequiredStringValue(diags, _item1.Type, _p1.AtName("type")),
		})
	}
	f := facets.NewHierarchyDatasetFacet(
		producer,
		hierarchyDatasetFacetLevel,
	)
	return f
}

func (m *OwnershipDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewOwnershipDatasetFacet(
		producer,
	)
	ownershipDatasetFacetOwner := make([]facets.OwnershipDatasetFacetOwner, 0, len(m.Owners))
	for _i1, _item1 := range m.Owners {
		_p1 := base.AtName("owners").AtListIndex(_i1)
		ownershipDatasetFacetOwner = append(ownershipDatasetFacetOwner, facets.OwnershipDatasetFacetOwner{
			Name: RequiredStringValue(diags, _item1.Name, _p1.AtName("name")),
			Type: OptionalStringValue(_item1.Type),
		})
	}
	f.Owners = ownershipDatasetFacetOwner
	return f
}

func (m *SchemaDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewSchemaDatasetFacet(
		producer,
	)
	schemaDatasetFacetFields := make([]facets.SchemaDatasetFacetFields, 0, len(m.Fields))
	for _i1, _item1 := range m.Fields {
		_p1 := base.AtName("fields").AtListIndex(_i1)
		schemaDatasetFacetFields = append(schemaDatasetFacetFields, facets.SchemaDatasetFacetFields{
			Description:     OptionalStringValue(_item1.Description),
			Name:            RequiredStringValue(diags, _item1.Name, _p1.AtName("name")),
			OrdinalPosition: OptionalInt64Value(_item1.OrdinalPosition),
			Type:            OptionalStringValue(_item1.Type),
		})
	}
	f.Fields = schemaDatasetFacetFields
	return f
}

func (m *StorageDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewStorageDatasetFacet(
		producer,
		RequiredStringValue(diags, m.StorageLayer, base.AtName("storage_layer")),
	)
	f.FileFormat = OptionalStringValue(m.FileFormat)
	return f
}

func (m *SymlinksDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewSymlinksDatasetFacet(
		producer,
	)
	symlinksDatasetFacetIdentifier := make([]facets.SymlinksDatasetFacetIdentifier, 0, len(m.Identifiers))
	for _i1, _item1 := range m.Identifiers {
		_p1 := base.AtName("identifiers").AtListIndex(_i1)
		symlinksDatasetFacetIdentifier = append(symlinksDatasetFacetIdentifier, facets.SymlinksDatasetFacetIdentifier{
			Name:      RequiredStringValue(diags, _item1.Name, _p1.AtName("name")),
			Namespace: RequiredStringValue(diags, _item1.Namespace, _p1.AtName("namespace")),
			Type:      RequiredStringValue(diags, _item1.Type, _p1.AtName("type")),
		})
	}
	f.Identifiers = symlinksDatasetFacetIdentifier
	return f
}

func (m *TagsDatasetFacetModel) BuildDatasetFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.DatasetFacet {
	f := facets.NewTagsDatasetFacet(
		producer,
	)
	tagsDatasetFacetFields := make([]facets.TagsDatasetFacetFields, 0, len(m.Tags))
	for _i1, _item1 := range m.Tags {
		_p1 := base.AtName("tags").AtListIndex(_i1)
		tagsDatasetFacetFields = append(tagsDatasetFacetFields, facets.TagsDatasetFacetFields{
			Field:  OptionalStringValue(_item1.Field),
			Key:    RequiredStringValue(diags, _item1.Key, _p1.AtName("key")),
			Source: OptionalStringValue(_item1.Source),
			Value:  RequiredStringValue(diags, _item1.Value, _p1.AtName("value")),
		})
	}
	f.Tags = tagsDatasetFacetFields
	return f
}

func (m *DocumentationJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewDocumentationJobFacet(
		producer,
		RequiredStringValue(diags, m.Description, base.AtName("description")),
	)
	f.ContentType = OptionalStringValue(m.ContentType)
	return f
}

func (m *JobTypeJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewJobTypeJobFacet(
		producer,
		RequiredStringValue(diags, m.Integration, base.AtName("integration")),
		RequiredStringValue(diags, m.ProcessingType, base.AtName("processing_type")),
	)
	f.JobType = OptionalStringValue(m.JobType)
	return f
}

func (m *OwnershipJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewOwnershipJobFacet(
		producer,
	)
	ownershipJobFacetOwner := make([]facets.OwnershipJobFacetOwner, 0, len(m.Owners))
	for _i1, _item1 := range m.Owners {
		_p1 := base.AtName("owners").AtListIndex(_i1)
		ownershipJobFacetOwner = append(ownershipJobFacetOwner, facets.OwnershipJobFacetOwner{
			Name: RequiredStringValue(diags, _item1.Name, _p1.AtName("name")),
			Type: OptionalStringValue(_item1.Type),
		})
	}
	f.Owners = ownershipJobFacetOwner
	return f
}

func (m *SQLJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewSQLJobFacet(
		producer,
		RequiredStringValue(diags, m.Query, base.AtName("query")),
	)
	f.Dialect = OptionalStringValue(m.Dialect)
	return f
}

func (m *SourceCodeJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewSourceCodeJobFacet(
		producer,
		RequiredStringValue(diags, m.Language, base.AtName("language")),
		RequiredStringValue(diags, m.SourceCode, base.AtName("source_code")),
	)
	return f
}

func (m *SourceCodeLocationJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewSourceCodeLocationJobFacet(
		producer,
		RequiredStringValue(diags, m.Type, base.AtName("type")),
		RequiredStringValue(diags, m.Url, base.AtName("url")),
	)
	f.Branch = OptionalStringValue(m.Branch)
	f.Path = OptionalStringValue(m.Path)
	f.PullRequestNumber = OptionalStringValue(m.PullRequestNumber)
	f.RepoURL = OptionalStringValue(m.RepoUrl)
	f.Tag = OptionalStringValue(m.Tag)
	f.Version = OptionalStringValue(m.Version)
	return f
}

func (m *TagsJobFacetModel) BuildJobFacet(producer string, diags *diag.Diagnostics, base path.Path) facets.JobFacet {
	f := facets.NewTagsJobFacet(
		producer,
	)
	tagsJobFacetFields := make([]facets.TagsJobFacetFields, 0, len(m.Tags))
	for _i1, _item1 := range m.Tags {
		_p1 := base.AtName("tags").AtListIndex(_i1)
		tagsJobFacetFields = append(tagsJobFacetFields, facets.TagsJobFacetFields{
			Key:    RequiredStringValue(diags, _item1.Key, _p1.AtName("key")),
			Source: OptionalStringValue(_item1.Source),
			Value:  RequiredStringValue(diags, _item1.Value, _p1.AtName("value")),
		})
	}
	f.Tags = tagsJobFacetFields
	return f
}
