/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CatalogDatasetFacetModel struct {
	CatalogProperties map[string]types.String `tfsdk:"catalog_properties"`
	Framework         types.String            `tfsdk:"framework"`
	MetadataUri       types.String            `tfsdk:"metadata_uri"`
	Name              types.String            `tfsdk:"name"`
	Source            types.String            `tfsdk:"source"`
	Type              types.String            `tfsdk:"type"`
	WarehouseUri      types.String            `tfsdk:"warehouse_uri"`
}

type ColumnLineageDatasetFacetModelDatasetTransformations struct {
	Description types.String `tfsdk:"description"`
	Masking     types.Bool   `tfsdk:"masking"`
	Subtype     types.String `tfsdk:"subtype"`
	Type        types.String `tfsdk:"type"`
}

type ColumnLineageDatasetFacetModelDataset struct {
	Field           types.String                                           `tfsdk:"field"`
	Name            types.String                                           `tfsdk:"name"`
	Namespace       types.String                                           `tfsdk:"namespace"`
	Transformations []ColumnLineageDatasetFacetModelDatasetTransformations `tfsdk:"transformations"`
}

type ColumnLineageDatasetFacetModelFields struct {
	InputFields []ColumnLineageDatasetFacetModelDataset `tfsdk:"input_fields"`
}

type ColumnLineageDatasetFacetModel struct {
	Dataset []ColumnLineageDatasetFacetModelDataset         `tfsdk:"dataset"`
	Fields  map[string]ColumnLineageDatasetFacetModelFields `tfsdk:"fields"`
}

type DatasetTypeDatasetFacetModel struct {
	DatasetType types.String `tfsdk:"dataset_type"`
	SubType     types.String `tfsdk:"sub_type"`
}

type DatasetVersionDatasetFacetModel struct {
	DatasetVersion types.String `tfsdk:"dataset_version"`
}

type DatasourceDatasetFacetModel struct {
	Name types.String `tfsdk:"name"`
	Uri  types.String `tfsdk:"uri"`
}

type DocumentationDatasetFacetModel struct {
	ContentType types.String `tfsdk:"content_type"`
	Description types.String `tfsdk:"description"`
}

type DocumentationJobFacetModel struct {
	ContentType types.String `tfsdk:"content_type"`
	Description types.String `tfsdk:"description"`
}

type HierarchyDatasetFacetModelHierarchy struct {
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

type HierarchyDatasetFacetModel struct {
	Hierarchy []HierarchyDatasetFacetModelHierarchy `tfsdk:"hierarchy"`
}

type JobTypeJobFacetModel struct {
	Integration    types.String `tfsdk:"integration"`
	JobType        types.String `tfsdk:"job_type"`
	ProcessingType types.String `tfsdk:"processing_type"`
}

type OwnershipDatasetFacetModelOwners struct {
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

type OwnershipDatasetFacetModel struct {
	Owners []OwnershipDatasetFacetModelOwners `tfsdk:"owners"`
}

type OwnershipJobFacetModelOwners struct {
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

type OwnershipJobFacetModel struct {
	Owners []OwnershipJobFacetModelOwners `tfsdk:"owners"`
}

type SQLJobFacetModel struct {
	Dialect types.String `tfsdk:"dialect"`
	Query   types.String `tfsdk:"query"`
}

type SchemaDatasetFacetModelFields struct {
	Description     types.String                    `tfsdk:"description"`
	Fields          []SchemaDatasetFacetModelFields `tfsdk:"fields"`
	Name            types.String                    `tfsdk:"name"`
	OrdinalPosition types.Int64                     `tfsdk:"ordinal_position"`
	Type            types.String                    `tfsdk:"type"`
}

type SchemaDatasetFacetModel struct {
	Fields []SchemaDatasetFacetModelFields `tfsdk:"fields"`
}

type SourceCodeJobFacetModel struct {
	Language   types.String `tfsdk:"language"`
	SourceCode types.String `tfsdk:"source_code"`
}

type SourceCodeLocationJobFacetModel struct {
	Branch            types.String `tfsdk:"branch"`
	Path              types.String `tfsdk:"path"`
	PullRequestNumber types.String `tfsdk:"pull_request_number"`
	RepoUrl           types.String `tfsdk:"repo_url"`
	Tag               types.String `tfsdk:"tag"`
	Type              types.String `tfsdk:"type"`
	Url               types.String `tfsdk:"url"`
	Version           types.String `tfsdk:"version"`
}

type StorageDatasetFacetModel struct {
	FileFormat   types.String `tfsdk:"file_format"`
	StorageLayer types.String `tfsdk:"storage_layer"`
}

type SymlinksDatasetFacetModelIdentifiers struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Type      types.String `tfsdk:"type"`
}

type SymlinksDatasetFacetModel struct {
	Identifiers []SymlinksDatasetFacetModelIdentifiers `tfsdk:"identifiers"`
}

type TagsDatasetFacetModelTags struct {
	Field  types.String `tfsdk:"field"`
	Key    types.String `tfsdk:"key"`
	Source types.String `tfsdk:"source"`
	Value  types.String `tfsdk:"value"`
}

type TagsDatasetFacetModel struct {
	Tags []TagsDatasetFacetModelTags `tfsdk:"tags"`
}

type TagsJobFacetModelTags struct {
	Key    types.String `tfsdk:"key"`
	Source types.String `tfsdk:"source"`
	Value  types.String `tfsdk:"value"`
}

type TagsJobFacetModel struct {
	Tags []TagsJobFacetModelTags `tfsdk:"tags"`
}
