/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by generator/go. DO NOT EDIT.

package ol

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type JobResourceModel struct {
	OLJobConfig
	Inputs  []OLInputModel  `tfsdk:"inputs"`
	Outputs []OLOutputModel `tfsdk:"outputs"`
}

type OLInputModel struct {
	DatasetModel
}

type OLOutputModel struct {
	DatasetModel
	ColumnLineage *ColumnLineageDatasetFacetModel `tfsdk:"column_lineage"`
}

type DatasetResourceModel struct {
	DatasetModel
}

type OLJobConfig struct {
	Namespace          types.String                     `tfsdk:"namespace"`
	Name               types.String                     `tfsdk:"name"`
	Description        types.String                     `tfsdk:"description"`
	Documentation      *DocumentationJobFacetModel      `tfsdk:"documentation"`
	JobType            *JobTypeJobFacetModel            `tfsdk:"job_type"`
	Ownership          *OwnershipJobFacetModel          `tfsdk:"ownership"`
	SQL                *SQLJobFacetModel                `tfsdk:"sql"`
	SourceCode         *SourceCodeJobFacetModel         `tfsdk:"source_code"`
	SourceCodeLocation *SourceCodeLocationJobFacetModel `tfsdk:"source_code_location"`
	Tags               *TagsJobFacetModel               `tfsdk:"tags"`
}

type DatasetModel struct {
	Namespace     types.String                     `tfsdk:"namespace"`
	Name          types.String                     `tfsdk:"name"`
	Catalog       *CatalogDatasetFacetModel        `tfsdk:"catalog"`
	DatasetType   *DatasetTypeDatasetFacetModel    `tfsdk:"dataset_type"`
	Version       *DatasetVersionDatasetFacetModel `tfsdk:"version"`
	DataSource    *DatasourceDatasetFacetModel     `tfsdk:"datasource"`
	Documentation *DocumentationDatasetFacetModel  `tfsdk:"documentation"`
	Hierarchy     *HierarchyDatasetFacetModel      `tfsdk:"hierarchy"`
	Ownership     *OwnershipDatasetFacetModel      `tfsdk:"ownership"`
	Schema        *SchemaDatasetFacetModel         `tfsdk:"schema"`
	Storage       *StorageDatasetFacetModel        `tfsdk:"storage"`
	Symlinks      *SymlinksDatasetFacetModel       `tfsdk:"symlinks"`
	Tags          *TagsDatasetFacetModel           `tfsdk:"tags"`
}
