/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os/exec"
	"strings"

	"golang.org/x/tools/go/ast/astutil"
)

func generateOpenLineageCode() (string, error) {
	quicktypeCommand := strings.Join([]string{
		"quicktype",
		"-l",
		"go",
		"--src-lang",
		"schema",
		"--package",
		"openlineage",
		"--top-level",
		"Event",
		"--just-types-and-package",
		"--no-ignore-json-refs",
		"../../spec/OpenLineage.json",
	}, " ")

	args := []string{
		"-c",
		quicktypeCommand,
	}

	cmd := exec.Command("bash", args...)
	result, err := cmd.Output()
	if err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			fmt.Println(string(exitError.Stderr))

		}
		return "", err
	}

	code := string(result)

	replacements := map[string]string{
		"package openlineage":         "/*\n * Copyright 2018-2026 contributors to the OpenLineage project\n * SPDX-License-Identifier: Apache-2.0\n */\n// Code generated by internal/generate; DO NOT EDIT.\n\npackage openlineage\n\nimport (\n\t\"time\"\n\n\t\"github.com/OpenLineage/openlineage/client/go/pkg/facets\"\n)\n",
		"map[string]InputFacetValue":  "*facets.InputDatasetFacets",
		"map[string]DatasetFacet":     "*facets.DatasetFacets",
		"map[string]JobFacet":         "*facets.JobFacets",
		"map[string]OutputFacetValue": "*facets.OutputDatasetFacets",
		"map[string]RunFacet":         "*facets.RunFacets",
		"import \"time\"":             "",
		"type Run struct":             "type RunInfo struct",
		"*Run ":                       "*RunInfo ",
		// Prefix EventType constants
		"Abort":    "EventTypeAbort",
		"Fail":     "EventTypeFail",
		"Complete": "EventTypeComplete",
		"Other":    "EventTypeOther",
		"Running":  "EventTypeRunning",
		"Start":    "EventTypeStart",
	}

	for k, v := range replacements {
		code = strings.ReplaceAll(code, k, v)
	}

	return code, nil
}

func removeFacetBaseTypes(code string) (string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "facets.gen.go", code, parser.ParseComments)
	if err != nil {
		return "", err
	}

	result := astutil.Apply(file, nil, func(c *astutil.Cursor) bool {
		n := c.Node()
		if x, ok := n.(*ast.GenDecl); ok {
			if x.Tok != token.TYPE && x.Tok != token.CONST {
				return true
			}

			if x.Tok == token.TYPE {
				spec := x.Specs[0].(*ast.TypeSpec)
				typeDeclName := spec.Name.String()

				deletions := []string{
					"InputFacetValue",
					"DatasetFacet",
					"JobFacet",
					"OutputFacetValue",
					"RunFacet",
				}

				for _, d := range deletions {
					if typeDeclName == d {
						c.Delete()
						return true
					}
				}

				// Fix doc comment to start with type name (revive exported rule)
				if x.Doc != nil && len(x.Doc.List) > 0 {
					existing := strings.TrimPrefix(x.Doc.List[0].Text, "// ")
					x.Doc.List[0].Text = "// " + typeDeclName + " — " + existing
				} else {
					x.Doc = &ast.CommentGroup{
						List: []*ast.Comment{{Text: "// " + typeDeclName + " is an OpenLineage type."}},
					}
				}
			}

			if x.Tok == token.CONST {
				// Add comment to const block if missing
				if x.Doc == nil {
					if len(x.Specs) > 0 {
						if vs, ok := x.Specs[0].(*ast.ValueSpec); ok && len(vs.Names) > 0 {
							name := vs.Names[0].Name
							x.Doc = &ast.CommentGroup{
								List: []*ast.Comment{{Text: "// " + name + " and related constants."}},
							}
						}
					}
				}
			}
		}

		return true
	})

	var out bytes.Buffer
	if err := format.Node(&out, fset, result); err != nil {
		return "", err
	}

	return out.String(), nil
}
