/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Package main implements the facet code generator.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
	"golang.org/x/tools/go/ast/astutil"

	_ "embed"
)

var (
	//go:embed facet_helpers.go.tmpl
	facetHelperTemplate string
)

type facetKind string

const (
	facetTypeInputDataset  = "InputDatasetFacet"
	facetTypeOutputDataset = "OutputDatasetFacet"
	facetTypeDataset       = "DatasetFacet"
	facetTypeJob           = "JobFacet"
	facetTypeRun           = "RunFacet"
)

type facetSpec struct {
	Name           string
	JSONName       string
	Tag            string
	Fields         []facetFieldSpec
	OptionalFields []facetFieldSpec
	Kind           facetKind
	Producer       string
	SchemaURL      string
}

type facetFieldSpec struct {
	Name         string
	ParamName    string
	Typ          string
	IsRefType    bool
	IsStructType bool
}

func generateFacets() (string, error) {
	quicktypeCommand := strings.Join([]string{
		"quicktype",
		"-l", "go",
		"--src-lang", "schema",
		"--package", "facets",
		"--just-types-and-package",
		"--no-ignore-json-refs",
		"--src", "../../spec/facets/*Facet.json",
		"--src", "../../spec/registry/*/facets/*Facet.json",
		"--src", "../../spec/registry/*/*/facets/*Facet.json",
	}, " ")

	cmd := exec.Command("bash", "-c", quicktypeCommand)
	result, err := cmd.Output()
	if err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			fmt.Println(string(exitError.Stderr))

		}
		return "", err
	}

	code := string(result)

	// Consolidate imports: quicktype scatters imports throughout the file
	code = consolidateImports(code)

	return code, nil
}

// consolidateImports finds all import statements scattered throughout the code,
// removes them from their original positions, and adds a single import block
// at the top of the file after the package declaration.
func consolidateImports(code string) string {
	lines := strings.Split(code, "\n")
	if len(lines) == 0 {
		return code
	}

	// Collect unique imports and filter out import lines from the rest
	imports := make(map[string]bool)
	var codeLines []string

	var packageLine = lines[0]
	for _, line := range lines[1:] {
		trimmed := strings.TrimSpace(line)

		// Check for single-line import: import "time"
		if strings.HasPrefix(trimmed, "import \"") {
			start := strings.Index(trimmed, "\"")
			end := strings.LastIndex(trimmed, "\"")
			if start != -1 && end > start {
				pkg := trimmed[start+1 : end]
				imports[pkg] = true
			}
			continue // Skip import lines
		}

		codeLines = append(codeLines, line)
	}

	// Build output: copyright + generated marker + package + imports + code
	var output strings.Builder
	output.WriteString("/*\n")
	output.WriteString(" * Copyright 2018-2026 contributors to the OpenLineage project\n")
	output.WriteString(" * SPDX-License-Identifier: Apache-2.0\n")
	output.WriteString(" */\n")
	output.WriteString("// Code generated by internal/generate; DO NOT EDIT.\n\n")

	output.WriteString(packageLine + "\n")

	if len(imports) > 0 {
		output.WriteString("\nimport (\n")
		for pkg := range imports {
			fmt.Fprintf(&output, "\t%q\n", pkg)
		}
		output.WriteString(")\n")
	}

	output.WriteString(strings.Join(codeLines, "\n"))

	return output.String()
}

func extractFacets(code string) ([]facetSpec, error) {
	// Create a FileSet to work with
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "facets.gen.go", code, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var facets []facetSpec

	ast.Inspect(file, func(n ast.Node) bool {
		// Find Function Call Statements
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		wrapperName := typeSpec.Name.String()
		if !strings.HasSuffix(wrapperName, "Facet") {
			return true
		}

		kind, err := deduceFacetKind(wrapperName)
		if err != nil {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		if len(structType.Fields.List) != 1 {
			return false
		}

		facetField := structType.Fields.List[0]

		// Handle both pointer (*Type) and non-pointer (Type) field types
		var facetIdent *ast.Ident
		switch fieldType := facetField.Type.(type) {
		case *ast.StarExpr:
			// Pointer type: *SomeFacet
			ident, ok := fieldType.X.(*ast.Ident)
			if !ok {
				return true // skip unsupported pointer targets (e.g. *ast.InterfaceType)
			}
			facetIdent = ident
		case *ast.Ident:
			// Non-pointer type: SomeFacet
			facetIdent = fieldType
		default:
			// Unknown type, skip this facet
			return true
		}

		name := facetIdent.Name
		schemaURL, err := getSchemaURL(wrapperName)
		if err != nil {
			panic(err)
		}

		// Extract JSON field name from tag (e.g., `json:"subset,omitempty"` -> "subset")
		jsonName := extractJSONName(facetField.Tag.Value)

		facet := facetSpec{
			Tag:      facetField.Tag.Value,
			Name:     name,
			JSONName: jsonName,
			// Name:      facetField.Names[0].Name,
			Kind:      kind,
			Producer:  "openlineage-go",
			SchemaURL: schemaURL,
		}

		facetTypeSpec, ok := facetIdent.Obj.Decl.(*ast.TypeSpec)
		if !ok {
			panic(1)
		}

		facetStruct, ok := facetTypeSpec.Type.(*ast.StructType)
		if !ok {
			panic(1)
		}

		for _, f := range facetStruct.Fields.List {
			fName := f.Names[0].String()
			if fName == "SchemaURL" || fName == "Producer" {
				continue
			}

			var fType string
			var optional bool
			var isRefType bool
			var isStructType bool

			switch x := f.Type.(type) {
			case *ast.StarExpr:
				// Handle pointer types like *string, *int64
				switch inner := x.X.(type) {
				case *ast.Ident:
					fType = inner.Name
					// Capitalized idents are struct types, lowercase are builtins
					if inner.Name != "" && inner.Name[0] >= 'A' && inner.Name[0] <= 'Z' {
						isStructType = true
					}
				case *ast.SelectorExpr:
					// *time.Time -> time.Time
					fType = fmt.Sprintf("%s.%s", inner.X.(*ast.Ident).Name, inner.Sel.Name)
					isStructType = true
				default:
					continue // Skip unsupported types
				}
				optional = true
				if isStructType {
					isRefType = true // treat structs as ref types (passed by pointer)
				}
			case *ast.Ident:
				fType = x.Name
			case *ast.SelectorExpr:
				// time.Time
				fType = fmt.Sprintf("%s.%s", x.X.(*ast.Ident).Name, x.Sel.Name)
			case *ast.ArrayType:
				switch elem := x.Elt.(type) {
				case *ast.Ident:
					fType = fmt.Sprintf("[]%s", elem.Name)
				case *ast.SelectorExpr:
					pkg, ok := elem.X.(*ast.Ident)
					if !ok {
						continue
					}
					fType = fmt.Sprintf("[]%s.%s", pkg.Name, elem.Sel.Name)
				default:
					continue // Skip unsupported types
				}
				optional = true
				isRefType = true
			case *ast.MapType:
				kIdent, ok := x.Key.(*ast.Ident)
				if !ok {
					continue
				}
				vIdent, ok := x.Value.(*ast.Ident)
				if !ok {
					continue
				}
				optional = true
				isRefType = true
				fType = fmt.Sprintf("map[%s]%s", kIdent.Name, vIdent.Name)
			}

			paramName := strcase.ToLowerCamel(fName)
			if paramName == "type" {
				paramName = "typ"
			}
			paramName = normalizeAcronyms(paramName)

			field := facetFieldSpec{
				Name:         fName,
				ParamName:    paramName,
				Typ:          fType,
				IsRefType:    isRefType,
				IsStructType: isStructType,
			}

			if optional {
				facet.OptionalFields = append(facet.OptionalFields, field)
			} else {
				facet.Fields = append(facet.Fields, field)
			}
		}

		facets = append(facets, facet)

		return true
	})

	return facets, nil
}

func generateFacetHelpers(facets []facetSpec) (string, error) {
	t := template.New("main")
	tmpl, err := t.Parse(facetHelperTemplate)
	if err != nil {
		return "", err
	}

	data := map[string]any{
		"facets": facets,
		"facetKinds": []string{
			facetTypeInputDataset,
			facetTypeOutputDataset,
			facetTypeDataset,
			facetTypeJob,
			facetTypeRun,
		},
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), nil // return unformatted if formatting fails
	}

	return string(formatted), nil
}

func deduceFacetKind(name string) (facetKind, error) {
	kinds := []facetKind{
		facetTypeInputDataset,
		facetTypeOutputDataset,
		facetTypeDataset,
		facetTypeJob,
		facetTypeRun,
	}

	for _, k := range kinds {
		if strings.HasSuffix(name, string(k)) {
			return k, nil
		}
	}

	return "", fmt.Errorf("can't deduce facetKind from %s", name)
}

func removeFacetWrappers(code string) (string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "facets.gen.go", code, parser.ParseComments)
	if err != nil {
		return "", err
	}

	result := astutil.Apply(file, nil, func(c *astutil.Cursor) bool {
		n := c.Node()
		if x, ok := n.(*ast.GenDecl); ok {
			if x.Tok != token.TYPE && x.Tok != token.CONST {
				return true
			}

			if x.Tok == token.TYPE {
				spec := x.Specs[0].(*ast.TypeSpec)
				typeDeclName := spec.Name.String()
				if strings.HasSuffix(typeDeclName, "Facet") {
					c.Delete()
					return true
				}

				// Fix doc comment to start with the type name (revive exported rule)
				if x.Doc != nil && len(x.Doc.List) > 0 {
					existing := strings.TrimPrefix(x.Doc.List[0].Text, "// ")
					x.Doc.List[0].Text = "// " + typeDeclName + " — " + existing
				} else {
					x.Doc = &ast.CommentGroup{
						List: []*ast.Comment{{Text: "// " + typeDeclName + " is an OpenLineage facet type."}},
					}
				}
			}

			if x.Tok == token.CONST {
				if x.Doc == nil && len(x.Specs) > 0 {
					if vs, ok := x.Specs[0].(*ast.ValueSpec); ok && len(vs.Names) > 0 {
						name := vs.Names[0].Name
						x.Doc = &ast.CommentGroup{
							List: []*ast.Comment{{Text: "// " + name + " and related constants."}},
						}
					}
				}
			}
		}

		return true
	})

	var out bytes.Buffer
	if err := format.Node(&out, fset, result); err != nil {
		return "", err
	}

	// Prepend copyright header back
	return out.String(), nil
}

// getSchemaURL reads the JSONSchema for a facet and returns its $id.
// wrapperName is the full wrapper type name (e.g., "ErrorMessageRunFacet").
// It searches spec/facets and spec/registry/**/facets/.
func getSchemaURL(wrapperName string) (string, error) {
	globs := []string{
		fmt.Sprintf("../../spec/facets/%s.json", wrapperName),
		fmt.Sprintf("../../spec/registry/*/facets/%s.json", wrapperName),
		fmt.Sprintf("../../spec/registry/*/*/facets/%s.json", wrapperName),
	}

	var candidates []string
	for _, pattern := range globs {
		matches, err := filepath.Glob(pattern)
		if err == nil {
			candidates = append(candidates, matches...)
		}
	}

	for _, path := range candidates {
		f, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		var schema map[string]any
		if err := json.Unmarshal(f, &schema); err != nil {
			return "", err
		}

		id, ok := schema["$id"]
		if !ok {
			return "", fmt.Errorf("$id field not found in %s", path)
		}

		return id.(string), nil
	}

	return "", fmt.Errorf("schema file not found for %s", wrapperName)
}

// normalizeAcronyms replaces common suffix patterns that violate Go naming conventions.
// e.g., externalQueryId → externalQueryID, repoUrl → repoURL
func normalizeAcronyms(name string) string {
	replacements := [][2]string{
		{"Uuid", "UUID"},
		{"Uri", "URI"},
		{"Url", "URL"},
		{"Id", "ID"},
	}

	for _, r := range replacements {
		from, to := r[0], r[1]
		if strings.HasSuffix(name, from) {
			prefix := name[:len(name)-len(from)]
			if prefix == "" {
				// standalone: url → urlValue, id → id (keep lowercase)
				return strings.ToLower(from) + "Value"
			}
			return prefix + to
		}
	}

	return name
}

// extractJSONName extracts the JSON field name from a struct tag
// e.g., `json:"subset,omitempty"` -> "subset"
func extractJSONName(tag string) string {
	// Remove backticks
	tag = strings.Trim(tag, "`")

	// Find json:"..."
	const prefix = `json:"`
	start := strings.Index(tag, prefix)
	if start == -1 {
		return ""
	}
	start += len(prefix)

	// Find closing quote
	end := strings.Index(tag[start:], `"`)
	if end == -1 {
		return ""
	}

	jsonTag := tag[start : start+end]

	// Handle "name,omitempty" -> "name"
	if comma := strings.Index(jsonTag, ","); comma != -1 {
		return jsonTag[:comma]
	}

	return jsonTag
}
