/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shaded_io_openlineage_sql_OpenLineageSql */

#ifndef _Included_shaded_io_openlineage_sql_OpenLineageSql
#define _Included_shaded_io_openlineage_sql_OpenLineageSql
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shaded_io_openlineage_sql_OpenLineageSql
 * Method:    parse
 * Signature: (Ljava/util/List;Ljava/lang/String;Ljava/lang/String;)Lshaded/io/openlineage/sql/SqlMeta;
 */
JNIEXPORT jobject JNICALL Java_shaded_io_openlineage_sql_OpenLineageSql_parse
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     shaded_io_openlineage_sql_OpenLineageSql
 * Method:    provider
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_shaded_io_openlineage_sql_OpenLineageSql_provider
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
