/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by facet-gen. DO NOT EDIT.

package openlineage

import (
	"time"

	"github.com/OpenLineage/openlineage/client/go/pkg/facets"
)

// EventType — the current transition of the run state. It is required to issue 1 START event and 1 of [ COMPLETE, ABORT, FAIL ] event per run. Additional events with OTHER eventType can be added to the same run. For example to send additional metadata after the run is complete
type EventType string

const (
	EventTypeStart    EventType = "START"
	EventTypeRunning  EventType = "RUNNING"
	EventTypeComplete EventType = "COMPLETE"
	EventTypeAbort    EventType = "ABORT"
	EventTypeFail     EventType = "FAIL"
	EventTypeOther    EventType = "OTHER"
)

// BaseEvent contains the fields common to all OpenLineage event types.
type BaseEvent struct {
	// the time the event occurred at
	EventTime time.Time `json:"eventTime"`
	// URI identifying the producer of this metadata. For example this could be a git url with a given tag or sha
	Producer string `json:"producer"`
	// The JSON Pointer (https://tools.ietf.org/html/rfc6901) URL to the corresponding version of the schema definition for this RunEvent
	SchemaURL string `json:"schemaURL"`
}

// RunEvent — RunEvent represents an OpenLineage run lifecycle event.
type RunEvent struct {
	BaseEvent
	// the current transition of the run state. It is required to issue 1 START event and 1 of [ COMPLETE, ABORT, FAIL ] event per run. Additional events with OTHER eventType can be added to the same run. For example to send additional metadata after the run is complete
	EventType *EventType `json:"eventType,omitempty"`
	// The set of **input** datasets.
	Inputs []InputElement `json:"inputs,omitempty"`
	Job    Job            `json:"job"`
	// The set of **output** datasets.
	Outputs []OutputElement `json:"outputs,omitempty"`
	Run     Run             `json:"run"`
}

// DatasetEvent — DatasetEvent represents an OpenLineage static dataset metadata event.
type DatasetEvent struct {
	BaseEvent
	Dataset Dataset `json:"dataset"`
}

// JobEvent — JobEvent represents an OpenLineage job metadata event.
type JobEvent struct {
	BaseEvent
	// The set of **input** datasets.
	Inputs []InputElement `json:"inputs,omitempty"`
	Job    Job            `json:"job"`
	// The set of **output** datasets.
	Outputs []OutputElement `json:"outputs,omitempty"`
}

func (*RunEvent) openlineageEvent()     {}
func (*DatasetEvent) openlineageEvent() {}
func (*JobEvent) openlineageEvent()     {}

// Run
type Run struct {
	// The run facets.
	Facets *facets.RunFacets `json:"facets,omitempty"`
	// The globally unique ID of the run associated with the job.
	RunID string `json:"runId"`
}

// Job
type Job struct {
	// The job facets.
	Facets *facets.JobFacets `json:"facets,omitempty"`
	// The unique name for that job within that namespace
	Name string `json:"name"`
	// The namespace containing that job
	Namespace string `json:"namespace"`
}

// Dataset — A Dataset sent within static metadata events
type Dataset struct {
	// The facets for this dataset
	Facets *facets.DatasetFacets `json:"facets,omitempty"`
	// The unique name for that dataset within that namespace
	Name string `json:"name"`
	// The namespace containing that dataset
	Namespace string `json:"namespace"`
}

// InputElement — An input dataset
type InputElement struct {
	// The facets for this dataset
	Facets *facets.DatasetFacets `json:"facets,omitempty"`
	// The input facets for this dataset.
	InputFacets *facets.InputDatasetFacets `json:"inputFacets,omitempty"`
	// The unique name for that dataset within that namespace
	Name string `json:"name"`
	// The namespace containing that dataset
	Namespace string `json:"namespace"`
}

// OutputElement — An output dataset
type OutputElement struct {
	// The facets for this dataset
	Facets *facets.DatasetFacets `json:"facets,omitempty"`
	// The unique name for that dataset within that namespace
	Name string `json:"name"`
	// The namespace containing that dataset
	Namespace string `json:"namespace"`
	// The output facets for this dataset
	OutputFacets *facets.OutputDatasetFacets `json:"outputFacets,omitempty"`
}
