[tool.ruff]
line-length = 110
select = [
    "F",
    "E",
    "W",
    "I001"
]
target-version = "py39"
ignore-init-module-imports = true
src = ["openlineage", "tests"]
namespace-packages = ["openlineage/dagster"]