workflows:
  openlineage-proxy-fluentd:
    jobs:
      - build-proxy-fluentd
      - release-docker-proxy-backend:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - build-proxy-fluentd
      - workflow_complete:
          requires:
            - build-proxy-fluentd
            - release-docker-proxy-backend