workflows:
  openlineage-website:
    jobs:
      - build-website:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - build-website
