workflows:
  openlineage-integration-publish:
    jobs:
      - publish-snapshot-python:
          filters:
            branches:
              only: main
          context: release
          requires:
            - build-client-python
            - build-integration-common
            - build-integration-airflow
            - build-integration-dbt
            - build-integration-dagster
            - build-integration-sql
      - publish-spec:
          filters:
            branches:
              only: main
          context: release
      - workflow_complete:
          requires:
            - publish-snapshot-python
            - publish-spec
