workflows:
  openlineage-proxy-backend:
    jobs:
      - build-proxy-backend
      - build-image-proxy-backend:
          requires:
            - build-proxy-backend
      - release-proxy-backend:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - build-image-proxy-backend
      - workflow_complete:
          requires:
            - build-proxy-backend
            - build-image-proxy-backend
            - release-proxy-backend