workflows:
  openlineage-integration-publish:
    jobs:
      - publish-spec:
          filters:
            branches:
              only: main
          context: release
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - publish-spec
