openapi: 3.0.2
info:
  title: OpenLineage
  version: 0.0.1
  description: OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /lineage:
    post:
      summary: Send an event related to the state of a run, job, or a dataset
      description: Updates a state of a run, job, or a dataset. 
      operationId: postRunEvent
      tags:
        - OpenLineage
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "OpenLineage.json#/$defs/RunEvent"
                - $ref: "OpenLineage.json#/$defs/DatasetEvent"
                - $ref: "OpenLineage.json#/$defs/JobEvent"
      responses:
        "200":
          description: OK
  /lineage/batch:
    post:
      summary: Send a batch of events related to the state of a run, job, or a dataset
      description: A batch of events with updates of a state of a run, job, or a dataset. 
      operationId: postEventBatch
      tags:
        - OpenLineage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  - $ref: "OpenLineage.json#/$defs/RunEvent"
                  - $ref: "OpenLineage.json#/$defs/DatasetEvent"
                  - $ref: "OpenLineage.json#/$defs/JobEvent"
      responses:
        "200":
          description: OK        
