DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;

CREATE TABLE t1 (a int, b string);
CREATE TABLE t2 (a int, b string);

INSERT INTO t1 SELECT a, concat(b, 'x') FROM t2;

DROP TABLE t1;
DROP TABLE t2;
