/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */

// Package spec generates the OpenLineage core event and entity types from OpenLineage.json.
package spec

import (
	"fmt"
	"sort"
	"strings"

	"github.com/atombender/go-jsonschema/pkg/schemas"

	"github.com/OpenLineage/openlineage/generator/go/genutil"
)// schemaToGoName maps $defs names that differ from their Go type names.
var schemaToGoName = map[string]string{
	"Run":           "Run",
	"InputDataset":  "InputElement",
	"OutputDataset": "OutputElement",
	"StaticDataset": "Dataset",
}

// facetContainerMap maps a facet base-type $defs name to the typed Go container.
var facetContainerMap = map[string]string{
	"RunFacet":           "*facets.RunFacets",
	"JobFacet":           "*facets.JobFacets",
	"DatasetFacet":       "*facets.DatasetFacets",
	"InputDatasetFacet":  "*facets.InputDatasetFacets",
	"OutputDatasetFacet": "*facets.OutputDatasetFacets",
}

// RenderSpec generates the content of spec.gen.go from OpenLineage.json.
func RenderSpec(schema *schemas.Schema) string {
	defs := schema.Definitions
	var b strings.Builder

	b.WriteString(`/*
 * Copyright 2018-2026 contributors to the OpenLineage project
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by facet-gen. DO NOT EDIT.

package openlineage

import (
	"time"

	"github.com/OpenLineage/openlineage/client/go/pkg/facets"
)

`)

	emitEventTypeEnum(&b, defs)
	emitEventStructs(&b, defs)

	for _, entry := range []struct{ defName, goName string }{
		{"Run", "Run"},
		{"Job", "Job"},
		{"StaticDataset", "Dataset"},
		{"InputDataset", "InputElement"},
		{"OutputDataset", "OutputElement"},
	} {
		def := defs[entry.defName]
		if def == nil {
			continue
		}
		emitStruct(&b, entry.goName, def.Description, collectProperties(def, defs))
	}

	return b.String()
}

// ── Internal types ────────────────────────────────────────────────────────────

type fieldSpec struct {
	jsonName    string
	goName      string
	goType      string
	required    bool
	description string
}

// ── Emitters ──────────────────────────────────────────────────────────────────

func emitEventTypeEnum(b *strings.Builder, defs map[string]*schemas.Type) {
	runEvent := defs["RunEvent"]
	if runEvent == nil {
		return
	}
	var enumProp *schemas.Type
	for _, sub := range runEvent.AllOf {
		if p, ok := sub.Properties["eventType"]; ok {
			enumProp = p
			break
		}
	}
	if enumProp == nil || len(enumProp.Enum) == 0 {
		return
	}

	if enumProp.Description != "" {
		desc := oneLine(enumProp.Description)
		fmt.Fprintf(b, "// EventType — %s\n", desc)
	} else {
		b.WriteString("// EventType is an OpenLineage run state transition.\n")
	}
	b.WriteString("type EventType string\n\n")
	b.WriteString("const (\n")
	for _, v := range enumProp.Enum {
		s, ok := v.(string)
		if !ok || s == "" {
			continue
		}
		// Title-case the suffix: "ABORT" → "Abort"
		suffix := strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
		fmt.Fprintf(b, "\tEventType%s EventType = %q\n", suffix, s)
	}
	b.WriteString(")\n\n")
}

// emitEventStructs emits BaseEvent and the three typed event structs
// (RunEvent, DatasetEvent, JobEvent), each embedding BaseEvent.
// This replaces the old merged Event struct and makes required fields
// visible at the type level for each event variant.
func emitEventStructs(b *strings.Builder, defs map[string]*schemas.Type) {
	// ── BaseEvent ────────────────────────────────────────────────────────────
	base := defs["BaseEvent"]
	if base != nil {
		baseRequired := map[string]bool{}
		for _, r := range base.Required {
			baseRequired[r] = true
		}
		var fields []fieldSpec
		for jsonName, prop := range base.Properties {
			isReq := baseRequired[jsonName]
			fields = append(fields, fieldSpec{
				jsonName:    jsonName,
				goName:      genutil.FormatGoFieldName(export(jsonName)),
				goType:      propGoTypeNamed(prop, isReq, jsonName),
				required:    isReq,
				description: description(prop),
			})
		}
		sortFields(fields)
		b.WriteString("// BaseEvent contains the fields common to all OpenLineage event types.\n")
		b.WriteString("type BaseEvent struct {\n")
		for _, f := range fields {
			emitField(b, f)
		}
		b.WriteString("}\n\n")
	}

	// ── Typed event structs ──────────────────────────────────────────────────
	eventDescs := map[string]string{
		"RunEvent":     "RunEvent represents an OpenLineage run lifecycle event.",
		"DatasetEvent": "DatasetEvent represents an OpenLineage static dataset metadata event.",
		"JobEvent":     "JobEvent represents an OpenLineage job metadata event.",
	}
	for _, defName := range []string{"RunEvent", "DatasetEvent", "JobEvent"} {
		def := defs[defName]
		if def == nil {
			continue
		}
		required := map[string]bool{}
		props := map[string]*schemas.Type{}
		for _, sub := range def.AllOf {
			if sub.Ref != "" {
				continue // skip $ref to BaseEvent
			}
			for _, r := range sub.Required {
				required[r] = true
			}
			for k, v := range sub.Properties {
				if _, ok := props[k]; !ok {
					props[k] = v
				}
			}
		}
		var fields []fieldSpec
		for jsonName, prop := range props {
			isReq := required[jsonName]
			fields = append(fields, fieldSpec{
				jsonName:    jsonName,
				goName:      genutil.FormatGoFieldName(export(jsonName)),
				goType:      propGoTypeNamed(prop, isReq, jsonName),
				required:    isReq,
				description: description(prop),
			})
		}
		sortFields(fields)
		desc := oneLine(def.Description)
		if desc == "" {
			desc = eventDescs[defName]
		}
		fmt.Fprintf(b, "// %s — %s\n", defName, desc)
		fmt.Fprintf(b, "type %s struct {\n", defName)
		b.WriteString("\tBaseEvent\n")
		for _, f := range fields {
			emitField(b, f)
		}
		b.WriteString("}\n\n")
	}

	// ── Emittable marker methods ─────────────────────────────────────────────
	for _, name := range []string{"RunEvent", "DatasetEvent", "JobEvent"} {
		fmt.Fprintf(b, "func (*%s) openlineageEvent() {}\n", name)
	}
	b.WriteString("\n")
}

// emitEventStructs replaces the old merged Event struct.
func emitStruct(b *strings.Builder, goTypeName, desc string, fields []fieldSpec) {
	if desc != "" {
		fmt.Fprintf(b, "// %s — %s\n", goTypeName, oneLine(desc))
	} else {
		fmt.Fprintf(b, "// %s\n", goTypeName)
	}
	fmt.Fprintf(b, "type %s struct {\n", goTypeName)
	for _, f := range fields {
		emitField(b, f)
	}
	b.WriteString("}\n\n")
}

func emitField(b *strings.Builder, f fieldSpec) {
	if f.description != "" {
		fmt.Fprintf(b, "\t// %s\n", oneLine(f.description))
	}
	fmt.Fprintf(b, "\t%s %s `%s`\n", f.goName, f.goType, jsonTag(f.jsonName, f.required))
}

func jsonTag(jsonName string, required bool) string {
	if required {
		return fmt.Sprintf("json:%q", jsonName)
	}
	return fmt.Sprintf(`json:"%s,omitempty"`, jsonName)
}

// ── Property collection ───────────────────────────────────────────────────────

// collectProperties gathers all properties from a def, following allOf chains.
func collectProperties(t *schemas.Type, defs map[string]*schemas.Type) []fieldSpec {
	required := map[string]bool{}
	props := map[string]*schemas.Type{}
	gatherProps(t, defs, props, required)

	var fields []fieldSpec
	for jsonName, prop := range props {
		isReq := required[jsonName]
		fields = append(fields, fieldSpec{
			jsonName:    jsonName,
			goName:      genutil.FormatGoFieldName(export(jsonName)),
			goType:      propGoType(prop, isReq),
			required:    isReq,
			description: description(prop),
		})
	}
	sortFields(fields)
	return fields
}

func gatherProps(t *schemas.Type, defs map[string]*schemas.Type, props map[string]*schemas.Type, required map[string]bool) {
	if t == nil {
		return
	}
	for _, r := range t.Required {
		required[r] = true
	}
	for k, v := range t.Properties {
		if _, exists := props[k]; !exists {
			props[k] = v
		}
	}
	for _, sub := range t.AllOf {
		if sub.Ref != "" {
			if def, ok := defs[refName(sub.Ref)]; ok {
				gatherProps(def, defs, props, required)
			}
		} else {
			gatherProps(sub, defs, props, required)
		}
	}
}

// ── Type resolution ───────────────────────────────────────────────────────────

// propGoType resolves the Go type for a JSON Schema property.
// propName is the JSON property name; it is used to scope string-enum types
// (currently only "eventType" maps to the generated EventType named type).
func propGoType(t *schemas.Type, required bool) string {
	return propGoTypeNamed(t, required, "")
}

// propGoTypeNamed is the internal version that also receives propName so it can
// avoid typing every string enum as *EventType.
func propGoTypeNamed(t *schemas.Type, required bool, propName string) string {
	if t == nil {
		return "interface{}"
	}

	if t.Ref != "" {
		return refGoType(t.Ref, required)
	}

	// anyOf with additionalProperties $ref → typed facet container
	for _, ao := range t.AnyOf {
		if ao.AdditionalProperties != nil && ao.AdditionalProperties.Ref != "" {
			if ct := facetContainerMap[refName(ao.AdditionalProperties.Ref)]; ct != "" {
				return ct
			}
		}
	}

	ptype := ""
	if len(t.Type) > 0 {
		ptype = t.Type[0]
	}

	switch ptype {
	case "string":
		if t.Format == "date-time" {
			if required {
				return "time.Time"
			}
			return "*time.Time"
		}
		if len(t.Enum) > 0 && propName == "eventType" {
			if required {
				return "EventType"
			}
			return "*EventType"
		}
		if required {
			return "string"
		}
		return "*string"
	case "boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "integer":
		if required {
			return "int64"
		}
		return "*int64"
	case "array":
		if t.Items != nil && t.Items.Ref != "" {
			return "[]" + refGoElem(t.Items.Ref)
		}
		return "[]interface{}"
	}
	return "interface{}"
}

func refGoType(ref string, required bool) string {
	name := refName(ref)
	goType := schemaToGoName[name]
	if goType == "" {
		goType = name
	}
	if required {
		return goType
	}
	return "*" + goType
}

func refGoElem(ref string) string {
	name := refName(ref)
	if goType := schemaToGoName[name]; goType != "" {
		return goType
	}
	return name
}

func refName(ref string) string {
	const marker = "/$defs/"
	if idx := strings.LastIndex(ref, marker); idx >= 0 {
		return ref[idx+len(marker):]
	}
	return ref
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func description(t *schemas.Type) string {
	if t == nil {
		return ""
	}
	return t.Description
}

func oneLine(s string) string {
	return strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
}

func export(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func sortFields(fields []fieldSpec) {
	sort.Slice(fields, func(i, j int) bool {
		return fields[i].jsonName < fields[j].jsonName
	})
}
